/*
 * Copyright 2020 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.statbuilds.bukkit.database.jooq;


import com.rpkit.statbuilds.bukkit.database.jooq.tables.RpkitCharacterStatPoints;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitStatBuilds extends SchemaImpl {

    private static final long serialVersionUID = -989272584;

    /**
     * The reference instance of <code>rpkit_stat_builds</code>
     */
    public static final RpkitStatBuilds RPKIT_STAT_BUILDS = new RpkitStatBuilds();

    /**
     * The table <code>rpkit_stat_builds.rpkit_character_stat_points</code>.
     */
    public final RpkitCharacterStatPoints RPKIT_CHARACTER_STAT_POINTS = RpkitCharacterStatPoints.RPKIT_CHARACTER_STAT_POINTS;

    /**
     * No further instances allowed
     */
    private RpkitStatBuilds() {
        super("rpkit_stat_builds", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            RpkitCharacterStatPoints.RPKIT_CHARACTER_STAT_POINTS);
    }
}
