/*
 * Copyright 2020 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.statbuilds.bukkit.database.jooq;


import com.rpkit.statbuilds.bukkit.database.jooq.tables.RpkitCharacterStatPoints;


/**
 * Convenience access to all tables in rpkit_stat_builds
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>rpkit_stat_builds.rpkit_character_stat_points</code>.
     */
    public static final RpkitCharacterStatPoints RPKIT_CHARACTER_STAT_POINTS = RpkitCharacterStatPoints.RPKIT_CHARACTER_STAT_POINTS;
}
