/*
 * Copyright 2019 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.skills.bukkit.database.jooq.rpkit.tables.records;


import com.rpkit.skills.bukkit.database.jooq.rpkit.tables.RpkitSkillBinding;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitSkillBindingRecord extends UpdatableRecordImpl<RpkitSkillBindingRecord> implements Record4<Integer, Integer, byte[], String> {

    private static final long serialVersionUID = 1714213914;

    /**
     * Setter for <code>rpkit.rpkit_skill_binding.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rpkit.rpkit_skill_binding.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rpkit.rpkit_skill_binding.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rpkit.rpkit_skill_binding.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rpkit.rpkit_skill_binding.item</code>.
     */
    public void setItem(byte... value) {
        set(2, value);
    }

    /**
     * Getter for <code>rpkit.rpkit_skill_binding.item</code>.
     */
    public byte[] getItem() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>rpkit.rpkit_skill_binding.skill_name</code>.
     */
    public void setSkillName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rpkit.rpkit_skill_binding.skill_name</code>.
     */
    public String getSkillName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, byte[], String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, byte[], String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RpkitSkillBinding.RPKIT_SKILL_BINDING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RpkitSkillBinding.RPKIT_SKILL_BINDING.CHARACTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field3() {
        return RpkitSkillBinding.RPKIT_SKILL_BINDING.ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return RpkitSkillBinding.RPKIT_SKILL_BINDING.SKILL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component3() {
        return getItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSkillName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value3() {
        return getItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSkillName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitSkillBindingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitSkillBindingRecord value2(Integer value) {
        setCharacterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitSkillBindingRecord value3(byte... value) {
        setItem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitSkillBindingRecord value4(String value) {
        setSkillName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitSkillBindingRecord values(Integer value1, Integer value2, byte[] value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RpkitSkillBindingRecord
     */
    public RpkitSkillBindingRecord() {
        super(RpkitSkillBinding.RPKIT_SKILL_BINDING);
    }

    /**
     * Create a detached, initialised RpkitSkillBindingRecord
     */
    public RpkitSkillBindingRecord(Integer id, Integer characterId, byte[] item, String skillName) {
        super(RpkitSkillBinding.RPKIT_SKILL_BINDING);

        set(0, id);
        set(1, characterId);
        set(2, item);
        set(3, skillName);
    }
}
