/*
 * This file is generated by jOOQ.
 */
package com.rpkit.professions.bukkit.database.jooq.rpkit.tables.records;


import com.rpkit.professions.bukkit.database.jooq.rpkit.tables.RpkitCharacterProfessionExperience;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitCharacterProfessionExperienceRecord extends UpdatableRecordImpl<RpkitCharacterProfessionExperienceRecord> implements Record4<Integer, Integer, String, Integer> {

    private static final long serialVersionUID = 191517379;

    /**
     * Setter for <code>rpkit.rpkit_character_profession_experience.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rpkit.rpkit_character_profession_experience.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rpkit.rpkit_character_profession_experience.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rpkit.rpkit_character_profession_experience.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rpkit.rpkit_character_profession_experience.profession</code>.
     */
    public void setProfession(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rpkit.rpkit_character_profession_experience.profession</code>.
     */
    public String getProfession() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rpkit.rpkit_character_profession_experience.experience</code>.
     */
    public void setExperience(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>rpkit.rpkit_character_profession_experience.experience</code>.
     */
    public Integer getExperience() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RpkitCharacterProfessionExperience.RPKIT_CHARACTER_PROFESSION_EXPERIENCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RpkitCharacterProfessionExperience.RPKIT_CHARACTER_PROFESSION_EXPERIENCE.CHARACTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return RpkitCharacterProfessionExperience.RPKIT_CHARACTER_PROFESSION_EXPERIENCE.PROFESSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return RpkitCharacterProfessionExperience.RPKIT_CHARACTER_PROFESSION_EXPERIENCE.EXPERIENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getProfession();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getExperience();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProfession();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getExperience();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitCharacterProfessionExperienceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitCharacterProfessionExperienceRecord value2(Integer value) {
        setCharacterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitCharacterProfessionExperienceRecord value3(String value) {
        setProfession(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitCharacterProfessionExperienceRecord value4(Integer value) {
        setExperience(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitCharacterProfessionExperienceRecord values(Integer value1, Integer value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RpkitCharacterProfessionExperienceRecord
     */
    public RpkitCharacterProfessionExperienceRecord() {
        super(RpkitCharacterProfessionExperience.RPKIT_CHARACTER_PROFESSION_EXPERIENCE);
    }

    /**
     * Create a detached, initialised RpkitCharacterProfessionExperienceRecord
     */
    public RpkitCharacterProfessionExperienceRecord(Integer id, Integer characterId, String profession, Integer experience) {
        super(RpkitCharacterProfessionExperience.RPKIT_CHARACTER_PROFESSION_EXPERIENCE);

        set(0, id);
        set(1, characterId);
        set(2, profession);
        set(3, experience);
    }
}
