/*
 * Copyright 2020 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.experience.bukkit.database.jooq.tables;


import com.rpkit.experience.bukkit.database.jooq.Keys;
import com.rpkit.experience.bukkit.database.jooq.tables.records.RpkitExperienceRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitExperience extends TableImpl<RpkitExperienceRecord> {

    private static final long serialVersionUID = 2009500764;

    /**
     * The reference instance of <code>rpkit_experience.rpkit_experience</code>
     */
    public static final RpkitExperience RPKIT_EXPERIENCE_ = new RpkitExperience();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitExperienceRecord> getRecordType() {
        return RpkitExperienceRecord.class;
    }

    /**
     * The column <code>rpkit_experience.rpkit_experience.character_id</code>.
     */
    public final TableField<RpkitExperienceRecord, Integer> CHARACTER_ID = createField(DSL.name("character_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit_experience.rpkit_experience.value</code>.
     */
    public final TableField<RpkitExperienceRecord, Integer> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>rpkit_experience.rpkit_experience</code> table reference
     */
    public RpkitExperience() {
        this(DSL.name("rpkit_experience"), null);
    }

    /**
     * Create an aliased <code>rpkit_experience.rpkit_experience</code> table reference
     */
    public RpkitExperience(String alias) {
        this(DSL.name(alias), RPKIT_EXPERIENCE_);
    }

    /**
     * Create an aliased <code>rpkit_experience.rpkit_experience</code> table reference
     */
    public RpkitExperience(Name alias) {
        this(alias, RPKIT_EXPERIENCE_);
    }

    private RpkitExperience(Name alias, Table<RpkitExperienceRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitExperience(Name alias, Table<RpkitExperienceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> RpkitExperience(Table<O> child, ForeignKey<O, RpkitExperienceRecord> key) {
        super(child, key, RPKIT_EXPERIENCE_);
    }

    @Override
    public Schema getSchema() {
        return com.rpkit.experience.bukkit.database.jooq.RpkitExperience.RPKIT_EXPERIENCE;
    }

    @Override
    public UniqueKey<RpkitExperienceRecord> getPrimaryKey() {
        return Keys.KEY_RPKIT_EXPERIENCE_PRIMARY;
    }

    @Override
    public List<UniqueKey<RpkitExperienceRecord>> getKeys() {
        return Arrays.<UniqueKey<RpkitExperienceRecord>>asList(Keys.KEY_RPKIT_EXPERIENCE_PRIMARY);
    }

    @Override
    public RpkitExperience as(String alias) {
        return new RpkitExperience(DSL.name(alias), this);
    }

    @Override
    public RpkitExperience as(Name alias) {
        return new RpkitExperience(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitExperience rename(String name) {
        return new RpkitExperience(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitExperience rename(Name name) {
        return new RpkitExperience(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
