/*
 * This file is generated by jOOQ.
 */
package com.rpkit.experience.bukkit.database.jooq.tables;


import com.rpkit.experience.bukkit.database.jooq.Keys;
import com.rpkit.experience.bukkit.database.jooq.tables.records.RpkitExperienceRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitExperience extends TableImpl<RpkitExperienceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rpkit_experience.rpkit_experience</code>
     */
    public static final RpkitExperience RPKIT_EXPERIENCE_ = new RpkitExperience();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitExperienceRecord> getRecordType() {
        return RpkitExperienceRecord.class;
    }

    /**
     * The column <code>rpkit_experience.rpkit_experience.character_id</code>.
     */
    public final TableField<RpkitExperienceRecord, Integer> CHARACTER_ID = createField(DSL.name("character_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit_experience.rpkit_experience.value</code>.
     */
    public final TableField<RpkitExperienceRecord, Integer> VALUE = createField(DSL.name("value"), SQLDataType.INTEGER.nullable(false), this, "");

    private RpkitExperience(Name alias, Table<RpkitExperienceRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitExperience(Name alias, Table<RpkitExperienceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>rpkit_experience.rpkit_experience</code> table reference
     */
    public RpkitExperience(String alias) {
        this(DSL.name(alias), RPKIT_EXPERIENCE_);
    }

    /**
     * Create an aliased <code>rpkit_experience.rpkit_experience</code> table reference
     */
    public RpkitExperience(Name alias) {
        this(alias, RPKIT_EXPERIENCE_);
    }

    /**
     * Create a <code>rpkit_experience.rpkit_experience</code> table reference
     */
    public RpkitExperience() {
        this(DSL.name("rpkit_experience"), null);
    }

    public <O extends Record> RpkitExperience(Table<O> child, ForeignKey<O, RpkitExperienceRecord> key) {
        super(child, key, RPKIT_EXPERIENCE_);
    }

    @Override
    public Schema getSchema() {
        return com.rpkit.experience.bukkit.database.jooq.RpkitExperience.RPKIT_EXPERIENCE;
    }

    @Override
    public UniqueKey<RpkitExperienceRecord> getPrimaryKey() {
        return Keys.KEY_RPKIT_EXPERIENCE_PRIMARY;
    }

    @Override
    public List<UniqueKey<RpkitExperienceRecord>> getKeys() {
        return Arrays.<UniqueKey<RpkitExperienceRecord>>asList(Keys.KEY_RPKIT_EXPERIENCE_PRIMARY);
    }

    @Override
    public RpkitExperience as(String alias) {
        return new RpkitExperience(DSL.name(alias), this);
    }

    @Override
    public RpkitExperience as(Name alias) {
        return new RpkitExperience(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitExperience rename(String name) {
        return new RpkitExperience(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitExperience rename(Name name) {
        return new RpkitExperience(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
