name: rpk-rolling-bukkit
author: alyphen
version: @version@
main: com.rpkit.rolling.bukkit.RPKRollingBukkit
depend:
- rpk-core-bukkit
- rpk-player-lib-bukkit
- rpk-character-lib-bukkit
api-version: '1.18'
commands:
  roll:
    description: Rolls
    usage: /<command> [roll]
  privateroll:
    description: Rolls privately
    usage: /<command> [roll]
    aliases: [proll, rollscreen, dmroll]
permissions:
  rpkit.rolling.command.roll:
    description: Allows rolling
    default: true
  rpkit.rolling.command.privateroll:
    description: Allows private rolls
    default: op