name: rpk-unconsciousness-lib-bukkit
author: alyphen
version: @version@
main: com.rpkit.unconsciousness.bukkit.RPKUnconsciousnessLibBukkit
depend:
- rpk-core-bukkit
- rpk-player-lib-bukkit
- rpk-character-lib-bukkit
api-version: '1.16'