name: rpk-travel-bukkit
author: alyphen
version: @version@
main: com.rpkit.travel.bukkit.RPKTravelBukkit
depend:
- rpk-core-bukkit
- rpk-player-lib-bukkit
- rpk-warp-lib-bukkit
api-version: '1.15'
commands:
  deletewarp:
    description: Deletes a warp
    usage: /<command> [name]
  setwarp:
    description: Sets a warp at your current location
    usage: /<command> [name]
  warp:
    description: Warps to a location
    usage: /<command> [warp]
permissions:
  rpkit.travel.command.deletewarp:
    description: Allows you to delete a warp
    default: op
  rpkit.travel.command.setwarp:
    description: Allows you to set a warp
    default: op
  rpkit.travel.command.warp:
    description: Allows you to use warps
    default: op
  rpkit.travel.sign.warp.create:
    description: Allows the creation of warp signs
    default: op