/*
 * Copyright 2020 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.stores.bukkit.database.jooq;


import com.rpkit.stores.bukkit.database.jooq.tables.RpkitConsumablePurchase;
import com.rpkit.stores.bukkit.database.jooq.tables.RpkitConsumableStoreItem;
import com.rpkit.stores.bukkit.database.jooq.tables.RpkitPermanentPurchase;
import com.rpkit.stores.bukkit.database.jooq.tables.RpkitPermanentStoreItem;
import com.rpkit.stores.bukkit.database.jooq.tables.RpkitPurchase;
import com.rpkit.stores.bukkit.database.jooq.tables.RpkitStoreItem;
import com.rpkit.stores.bukkit.database.jooq.tables.RpkitTimedPurchase;
import com.rpkit.stores.bukkit.database.jooq.tables.RpkitTimedStoreItem;


/**
 * Convenience access to all tables in rpkit_stores
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>rpkit_stores.rpkit_consumable_purchase</code>.
     */
    public static final RpkitConsumablePurchase RPKIT_CONSUMABLE_PURCHASE = RpkitConsumablePurchase.RPKIT_CONSUMABLE_PURCHASE;

    /**
     * The table <code>rpkit_stores.rpkit_consumable_store_item</code>.
     */
    public static final RpkitConsumableStoreItem RPKIT_CONSUMABLE_STORE_ITEM = RpkitConsumableStoreItem.RPKIT_CONSUMABLE_STORE_ITEM;

    /**
     * The table <code>rpkit_stores.rpkit_permanent_purchase</code>.
     */
    public static final RpkitPermanentPurchase RPKIT_PERMANENT_PURCHASE = RpkitPermanentPurchase.RPKIT_PERMANENT_PURCHASE;

    /**
     * The table <code>rpkit_stores.rpkit_permanent_store_item</code>.
     */
    public static final RpkitPermanentStoreItem RPKIT_PERMANENT_STORE_ITEM = RpkitPermanentStoreItem.RPKIT_PERMANENT_STORE_ITEM;

    /**
     * The table <code>rpkit_stores.rpkit_purchase</code>.
     */
    public static final RpkitPurchase RPKIT_PURCHASE = RpkitPurchase.RPKIT_PURCHASE;

    /**
     * The table <code>rpkit_stores.rpkit_store_item</code>.
     */
    public static final RpkitStoreItem RPKIT_STORE_ITEM = RpkitStoreItem.RPKIT_STORE_ITEM;

    /**
     * The table <code>rpkit_stores.rpkit_timed_purchase</code>.
     */
    public static final RpkitTimedPurchase RPKIT_TIMED_PURCHASE = RpkitTimedPurchase.RPKIT_TIMED_PURCHASE;

    /**
     * The table <code>rpkit_stores.rpkit_timed_store_item</code>.
     */
    public static final RpkitTimedStoreItem RPKIT_TIMED_STORE_ITEM = RpkitTimedStoreItem.RPKIT_TIMED_STORE_ITEM;
}
