/*
 * This file is generated by jOOQ.
*/
package com.rpkit.moderation.bukkit.database.jooq.rpkit;


import com.rpkit.moderation.bukkit.database.jooq.rpkit.tables.RpkitTicket;
import com.rpkit.moderation.bukkit.database.jooq.rpkit.tables.RpkitVanishState;
import com.rpkit.moderation.bukkit.database.jooq.rpkit.tables.RpkitWarning;
import com.rpkit.moderation.bukkit.database.jooq.rpkit.tables.records.RpkitTicketRecord;
import com.rpkit.moderation.bukkit.database.jooq.rpkit.tables.records.RpkitVanishStateRecord;
import com.rpkit.moderation.bukkit.database.jooq.rpkit.tables.records.RpkitWarningRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>rpkit</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RpkitTicketRecord, Integer> IDENTITY_RPKIT_TICKET = Identities0.IDENTITY_RPKIT_TICKET;
    public static final Identity<RpkitVanishStateRecord, Integer> IDENTITY_RPKIT_VANISH_STATE = Identities0.IDENTITY_RPKIT_VANISH_STATE;
    public static final Identity<RpkitWarningRecord, Integer> IDENTITY_RPKIT_WARNING = Identities0.IDENTITY_RPKIT_WARNING;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RpkitTicketRecord> KEY_RPKIT_TICKET_PRIMARY = UniqueKeys0.KEY_RPKIT_TICKET_PRIMARY;
    public static final UniqueKey<RpkitVanishStateRecord> KEY_RPKIT_VANISH_STATE_PRIMARY = UniqueKeys0.KEY_RPKIT_VANISH_STATE_PRIMARY;
    public static final UniqueKey<RpkitWarningRecord> KEY_RPKIT_WARNING_PRIMARY = UniqueKeys0.KEY_RPKIT_WARNING_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<RpkitTicketRecord, Integer> IDENTITY_RPKIT_TICKET = createIdentity(RpkitTicket.RPKIT_TICKET, RpkitTicket.RPKIT_TICKET.ID);
        public static Identity<RpkitVanishStateRecord, Integer> IDENTITY_RPKIT_VANISH_STATE = createIdentity(RpkitVanishState.RPKIT_VANISH_STATE, RpkitVanishState.RPKIT_VANISH_STATE.ID);
        public static Identity<RpkitWarningRecord, Integer> IDENTITY_RPKIT_WARNING = createIdentity(RpkitWarning.RPKIT_WARNING, RpkitWarning.RPKIT_WARNING.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<RpkitTicketRecord> KEY_RPKIT_TICKET_PRIMARY = createUniqueKey(RpkitTicket.RPKIT_TICKET, "KEY_rpkit_ticket_PRIMARY", RpkitTicket.RPKIT_TICKET.ID);
        public static final UniqueKey<RpkitVanishStateRecord> KEY_RPKIT_VANISH_STATE_PRIMARY = createUniqueKey(RpkitVanishState.RPKIT_VANISH_STATE, "KEY_rpkit_vanish_state_PRIMARY", RpkitVanishState.RPKIT_VANISH_STATE.ID);
        public static final UniqueKey<RpkitWarningRecord> KEY_RPKIT_WARNING_PRIMARY = createUniqueKey(RpkitWarning.RPKIT_WARNING, "KEY_rpkit_warning_PRIMARY", RpkitWarning.RPKIT_WARNING.ID);
    }
}
