caching:
  rpkit_discord_profile:
    id:
      enabled: true
      size: 20
  rpkit_github_profile:
    id:
      enabled: true
      size: 20
    name:
      enabled: true
      size: 20
  rpkit_irc_profile:
    id:
      enabled: true
      size: 20
  rpkit_minecraft_profile:
    id:
      enabled: true
      size: 20
    minecraft_uuid:
      enabled: true
      size: 20
  rpkit_profile:
    id:
      enabled: true
      size: 20