name: rpk-players-bukkit
version: @version@
main: com.rpkit.players.bukkit.RPKPlayersBukkit
author: alyphen
description: RPK Players implementation for Bukkit
depend:
- rpk-core-bukkit
- rpk-player-lib-bukkit
softdepend:
- rpk-chat-lib-bukkit
api-version: '1.17'
commands:
  profile:
    description: |
      Profile management command
      /profile create [name] [password] - creates a profile with the given name and password
      /profile login [name] [password] - links a profile with the given name and password
      /profile link [type] [name] - links the profile of the given type
      /profile confirmlink [type] [id] - confirms the link to the given profile
      /profile denylink [type] [id] - denies the link to the given profile
    usage: /<command> [create|login]
    aliases: [account, acc]
permissions:
  rpkit.players.command.profile.link:
    description: Allows linking other profiles
    default: true
  rpkit.players.command.profile.link.irc:
    description: Allows linking IRC profiles
    default: true
  rpkit.players.command.profile.link.minecraft:
    description: Allows linking Minecraft profiles
    default: true
  rpkit.players.command.profile.view.self:
    description: Allows viewing your own profile
    default: true
  rpkit.players.command.profile.view.other:
    description: Allows viewing other people's profiles
