/*
 * This file is generated by jOOQ.
 */
package com.rpkit.languages.bukkit.database.jooq;


import com.rpkit.languages.bukkit.database.jooq.tables.RpkitCharacterLanguage;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitLanguages extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rpkit_languages</code>
     */
    public static final RpkitLanguages RPKIT_LANGUAGES = new RpkitLanguages();

    /**
     * The table <code>rpkit_languages.rpkit_character_language</code>.
     */
    public final RpkitCharacterLanguage RPKIT_CHARACTER_LANGUAGE = RpkitCharacterLanguage.RPKIT_CHARACTER_LANGUAGE;

    /**
     * No further instances allowed
     */
    private RpkitLanguages() {
        super("rpkit_languages", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            RpkitCharacterLanguage.RPKIT_CHARACTER_LANGUAGE
        );
    }
}
