/*
 * Copyright 2020 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.professions.bukkit.database.jooq.tables;


import com.rpkit.professions.bukkit.database.jooq.Keys;
import com.rpkit.professions.bukkit.database.jooq.RpkitProfessions;
import com.rpkit.professions.bukkit.database.jooq.tables.records.RpkitCharacterProfessionRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitCharacterProfession extends TableImpl<RpkitCharacterProfessionRecord> {

    private static final long serialVersionUID = -337541667;

    /**
     * The reference instance of <code>rpkit_professions.rpkit_character_profession</code>
     */
    public static final RpkitCharacterProfession RPKIT_CHARACTER_PROFESSION = new RpkitCharacterProfession();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitCharacterProfessionRecord> getRecordType() {
        return RpkitCharacterProfessionRecord.class;
    }

    /**
     * The column <code>rpkit_professions.rpkit_character_profession.character_id</code>.
     */
    public final TableField<RpkitCharacterProfessionRecord, Integer> CHARACTER_ID = createField(DSL.name("character_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit_professions.rpkit_character_profession.profession</code>.
     */
    public final TableField<RpkitCharacterProfessionRecord, String> PROFESSION = createField(DSL.name("profession"), org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * Create a <code>rpkit_professions.rpkit_character_profession</code> table reference
     */
    public RpkitCharacterProfession() {
        this(DSL.name("rpkit_character_profession"), null);
    }

    /**
     * Create an aliased <code>rpkit_professions.rpkit_character_profession</code> table reference
     */
    public RpkitCharacterProfession(String alias) {
        this(DSL.name(alias), RPKIT_CHARACTER_PROFESSION);
    }

    /**
     * Create an aliased <code>rpkit_professions.rpkit_character_profession</code> table reference
     */
    public RpkitCharacterProfession(Name alias) {
        this(alias, RPKIT_CHARACTER_PROFESSION);
    }

    private RpkitCharacterProfession(Name alias, Table<RpkitCharacterProfessionRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitCharacterProfession(Name alias, Table<RpkitCharacterProfessionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> RpkitCharacterProfession(Table<O> child, ForeignKey<O, RpkitCharacterProfessionRecord> key) {
        super(child, key, RPKIT_CHARACTER_PROFESSION);
    }

    @Override
    public Schema getSchema() {
        return RpkitProfessions.RPKIT_PROFESSIONS;
    }

    @Override
    public UniqueKey<RpkitCharacterProfessionRecord> getPrimaryKey() {
        return Keys.KEY_RPKIT_CHARACTER_PROFESSION_PRIMARY;
    }

    @Override
    public List<UniqueKey<RpkitCharacterProfessionRecord>> getKeys() {
        return Arrays.<UniqueKey<RpkitCharacterProfessionRecord>>asList(Keys.KEY_RPKIT_CHARACTER_PROFESSION_PRIMARY, Keys.KEY_RPKIT_CHARACTER_PROFESSION_RPKIT_CHARACTER_PROFESSION_CHARACTER_ID_UINDEX);
    }

    @Override
    public RpkitCharacterProfession as(String alias) {
        return new RpkitCharacterProfession(DSL.name(alias), this);
    }

    @Override
    public RpkitCharacterProfession as(Name alias) {
        return new RpkitCharacterProfession(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitCharacterProfession rename(String name) {
        return new RpkitCharacterProfession(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitCharacterProfession rename(Name name) {
        return new RpkitCharacterProfession(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
