name: rpk-lock-lib-bukkit
author: alyphen
version: @version@
main: com.rpkit.locks.bukkit.RPKLockLibBukkit
depend:
- rpk-core-bukkit
- rpk-player-lib-bukkit
- rpk-character-lib-bukkit
api-version: '1.15'