# See https://docs.oracle.com/javase/8/docs/api/index.html?java/text/SimpleDateFormat.html
date-format: yyyy-MM-dd HH:mm:ss zzz
# Measured in seconds.
# Default applies to everything not set.
# For material list, see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# All edible materials as of Minecraft 1.16.5 are currently included here, along with a rough estimation of their IRL shelf life.
food-expiry:
  default: 259200
  APPLE: 2419200
  MUSHROOM_STEW: 86400
  BREAD: 604800
  PORKCHOP: 172800
  COOKED_PORKCHOP: 86400
  GOLDEN_APPLE: 2419200
  ENCHANTED_GOLDEN_APPLE: 2419200
  COD: 172800
  SALMON: 172800
  TROPICAL_FISH: 172800
  PUFFERFISH: 172800
  COOKED_COD: 86400
  COOKED_SALMON: 86400
  COOKIE: 604800
  MELON_SLICE: 345600
  DRIED_KELP: 315576000
  BEEF: 172800
  COOKED_BEEF: 86400
  CHICKEN: 172800
  COOKED_CHICKEN: 86400
  ROTTEN_FLESH: 0
  SPIDER_EYE: 0
  CARROT: 3024000
  POTATO: 1209600
  BAKED_POTATO: 86400
  POISONOUS_POTATO: 0
  GOLDEN_CARROT: 3024000
  PUMPKIN_PIE: 86400
  RABBIT: 172800
  COOKED_RABBIT: 86400
  RABBIT_STEW: 86400
  MUTTON: 172800
  COOKED_MUTTON: 86400
  CHORUS_FRUIT: 1814400
  BEETROOT: 7889400
  BEETROOT_SOUP: 86400
  SUSPICIOUS_STEW: 86400
  SWEET_BERRIES: 259200
  HONEY_BOTTLE: 315576000