/*
 * Copyright 2020 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.blocklog.bukkit.database.jooq.tables.records;


import com.rpkit.blocklog.bukkit.database.jooq.tables.RpkitBlockHistory;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitBlockHistoryRecord extends UpdatableRecordImpl<RpkitBlockHistoryRecord> implements Record5<Integer, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 41993814;

    /**
     * Setter for <code>rpkit_block_logging.rpkit_block_history.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rpkit_block_logging.rpkit_block_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rpkit_block_logging.rpkit_block_history.world</code>.
     */
    public void setWorld(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rpkit_block_logging.rpkit_block_history.world</code>.
     */
    public String getWorld() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rpkit_block_logging.rpkit_block_history.x</code>.
     */
    public void setX(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>rpkit_block_logging.rpkit_block_history.x</code>.
     */
    public Integer getX() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>rpkit_block_logging.rpkit_block_history.y</code>.
     */
    public void setY(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>rpkit_block_logging.rpkit_block_history.y</code>.
     */
    public Integer getY() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>rpkit_block_logging.rpkit_block_history.z</code>.
     */
    public void setZ(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>rpkit_block_logging.rpkit_block_history.z</code>.
     */
    public Integer getZ() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Integer, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RpkitBlockHistory.RPKIT_BLOCK_HISTORY.ID;
    }

    @Override
    public Field<String> field2() {
        return RpkitBlockHistory.RPKIT_BLOCK_HISTORY.WORLD;
    }

    @Override
    public Field<Integer> field3() {
        return RpkitBlockHistory.RPKIT_BLOCK_HISTORY.X;
    }

    @Override
    public Field<Integer> field4() {
        return RpkitBlockHistory.RPKIT_BLOCK_HISTORY.Y;
    }

    @Override
    public Field<Integer> field5() {
        return RpkitBlockHistory.RPKIT_BLOCK_HISTORY.Z;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getWorld();
    }

    @Override
    public Integer component3() {
        return getX();
    }

    @Override
    public Integer component4() {
        return getY();
    }

    @Override
    public Integer component5() {
        return getZ();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getWorld();
    }

    @Override
    public Integer value3() {
        return getX();
    }

    @Override
    public Integer value4() {
        return getY();
    }

    @Override
    public Integer value5() {
        return getZ();
    }

    @Override
    public RpkitBlockHistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RpkitBlockHistoryRecord value2(String value) {
        setWorld(value);
        return this;
    }

    @Override
    public RpkitBlockHistoryRecord value3(Integer value) {
        setX(value);
        return this;
    }

    @Override
    public RpkitBlockHistoryRecord value4(Integer value) {
        setY(value);
        return this;
    }

    @Override
    public RpkitBlockHistoryRecord value5(Integer value) {
        setZ(value);
        return this;
    }

    @Override
    public RpkitBlockHistoryRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RpkitBlockHistoryRecord
     */
    public RpkitBlockHistoryRecord() {
        super(RpkitBlockHistory.RPKIT_BLOCK_HISTORY);
    }

    /**
     * Create a detached, initialised RpkitBlockHistoryRecord
     */
    public RpkitBlockHistoryRecord(Integer id, String world, Integer x, Integer y, Integer z) {
        super(RpkitBlockHistory.RPKIT_BLOCK_HISTORY);

        set(0, id);
        set(1, world);
        set(2, x);
        set(3, y);
        set(4, z);
    }
}
