/*
 * This file is generated by jOOQ.
 */
package com.rpkit.players.bukkit.database.jooq;


import com.rpkit.players.bukkit.database.jooq.tables.RpkitDiscordProfile;
import com.rpkit.players.bukkit.database.jooq.tables.RpkitGithubProfile;
import com.rpkit.players.bukkit.database.jooq.tables.RpkitIrcProfile;
import com.rpkit.players.bukkit.database.jooq.tables.RpkitMinecraftProfile;
import com.rpkit.players.bukkit.database.jooq.tables.RpkitMinecraftProfileLinkRequest;
import com.rpkit.players.bukkit.database.jooq.tables.RpkitProfile;


/**
 * Convenience access to all tables in rpkit_players.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>rpkit_players.rpkit_discord_profile</code>.
     */
    public static final RpkitDiscordProfile RPKIT_DISCORD_PROFILE = RpkitDiscordProfile.RPKIT_DISCORD_PROFILE;

    /**
     * The table <code>rpkit_players.rpkit_github_profile</code>.
     */
    public static final RpkitGithubProfile RPKIT_GITHUB_PROFILE = RpkitGithubProfile.RPKIT_GITHUB_PROFILE;

    /**
     * The table <code>rpkit_players.rpkit_irc_profile</code>.
     */
    public static final RpkitIrcProfile RPKIT_IRC_PROFILE = RpkitIrcProfile.RPKIT_IRC_PROFILE;

    /**
     * The table <code>rpkit_players.rpkit_minecraft_profile</code>.
     */
    public static final RpkitMinecraftProfile RPKIT_MINECRAFT_PROFILE = RpkitMinecraftProfile.RPKIT_MINECRAFT_PROFILE;

    /**
     * The table
     * <code>rpkit_players.rpkit_minecraft_profile_link_request</code>.
     */
    public static final RpkitMinecraftProfileLinkRequest RPKIT_MINECRAFT_PROFILE_LINK_REQUEST = RpkitMinecraftProfileLinkRequest.RPKIT_MINECRAFT_PROFILE_LINK_REQUEST;

    /**
     * The table <code>rpkit_players.rpkit_profile</code>.
     */
    public static final RpkitProfile RPKIT_PROFILE = RpkitProfile.RPKIT_PROFILE;
}
