/*
 * Copyright 2020 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.locks.bukkit.database.jooq;


import com.rpkit.locks.bukkit.database.jooq.tables.RpkitKeyring;
import com.rpkit.locks.bukkit.database.jooq.tables.RpkitPlayerGettingKey;
import com.rpkit.locks.bukkit.database.jooq.tables.RpkitPlayerUnclaiming;
import com.rpkit.locks.bukkit.database.jooq.tables.records.RpkitKeyringRecord;
import com.rpkit.locks.bukkit.database.jooq.tables.records.RpkitPlayerGettingKeyRecord;
import com.rpkit.locks.bukkit.database.jooq.tables.records.RpkitPlayerUnclaimingRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>rpkit_locks</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RpkitKeyringRecord> KEY_RPKIT_KEYRING_PRIMARY = UniqueKeys0.KEY_RPKIT_KEYRING_PRIMARY;
    public static final UniqueKey<RpkitKeyringRecord> KEY_RPKIT_KEYRING_RPKIT_KEYRING_CHARACTER_ID_UINDEX = UniqueKeys0.KEY_RPKIT_KEYRING_RPKIT_KEYRING_CHARACTER_ID_UINDEX;
    public static final UniqueKey<RpkitPlayerGettingKeyRecord> KEY_RPKIT_PLAYER_GETTING_KEY_PRIMARY = UniqueKeys0.KEY_RPKIT_PLAYER_GETTING_KEY_PRIMARY;
    public static final UniqueKey<RpkitPlayerGettingKeyRecord> KEY_RPKIT_PLAYER_GETTING_KEY_RPKIT_PLAYER_GETTING_KEY_MINECRAFT_PROFILE_ID_UINDEX = UniqueKeys0.KEY_RPKIT_PLAYER_GETTING_KEY_RPKIT_PLAYER_GETTING_KEY_MINECRAFT_PROFILE_ID_UINDEX;
    public static final UniqueKey<RpkitPlayerUnclaimingRecord> KEY_RPKIT_PLAYER_UNCLAIMING_PRIMARY = UniqueKeys0.KEY_RPKIT_PLAYER_UNCLAIMING_PRIMARY;
    public static final UniqueKey<RpkitPlayerUnclaimingRecord> KEY_RPKIT_PLAYER_UNCLAIMING_RPKIT_PLAYER_UNCLAIMING_MINECRAFT_PROFILE_ID_UINDEX = UniqueKeys0.KEY_RPKIT_PLAYER_UNCLAIMING_RPKIT_PLAYER_UNCLAIMING_MINECRAFT_PROFILE_ID_UINDEX;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<RpkitKeyringRecord> KEY_RPKIT_KEYRING_PRIMARY = Internal.createUniqueKey(RpkitKeyring.RPKIT_KEYRING, "KEY_rpkit_keyring_PRIMARY", new TableField[] { RpkitKeyring.RPKIT_KEYRING.CHARACTER_ID }, true);
        public static final UniqueKey<RpkitKeyringRecord> KEY_RPKIT_KEYRING_RPKIT_KEYRING_CHARACTER_ID_UINDEX = Internal.createUniqueKey(RpkitKeyring.RPKIT_KEYRING, "KEY_rpkit_keyring_rpkit_keyring_character_id_uindex", new TableField[] { RpkitKeyring.RPKIT_KEYRING.CHARACTER_ID }, true);
        public static final UniqueKey<RpkitPlayerGettingKeyRecord> KEY_RPKIT_PLAYER_GETTING_KEY_PRIMARY = Internal.createUniqueKey(RpkitPlayerGettingKey.RPKIT_PLAYER_GETTING_KEY, "KEY_rpkit_player_getting_key_PRIMARY", new TableField[] { RpkitPlayerGettingKey.RPKIT_PLAYER_GETTING_KEY.MINECRAFT_PROFILE_ID }, true);
        public static final UniqueKey<RpkitPlayerGettingKeyRecord> KEY_RPKIT_PLAYER_GETTING_KEY_RPKIT_PLAYER_GETTING_KEY_MINECRAFT_PROFILE_ID_UINDEX = Internal.createUniqueKey(RpkitPlayerGettingKey.RPKIT_PLAYER_GETTING_KEY, "KEY_rpkit_player_getting_key_rpkit_player_getting_key_minecraft_profile_id_uindex", new TableField[] { RpkitPlayerGettingKey.RPKIT_PLAYER_GETTING_KEY.MINECRAFT_PROFILE_ID }, true);
        public static final UniqueKey<RpkitPlayerUnclaimingRecord> KEY_RPKIT_PLAYER_UNCLAIMING_PRIMARY = Internal.createUniqueKey(RpkitPlayerUnclaiming.RPKIT_PLAYER_UNCLAIMING, "KEY_rpkit_player_unclaiming_PRIMARY", new TableField[] { RpkitPlayerUnclaiming.RPKIT_PLAYER_UNCLAIMING.MINECRAFT_PROFILE_ID }, true);
        public static final UniqueKey<RpkitPlayerUnclaimingRecord> KEY_RPKIT_PLAYER_UNCLAIMING_RPKIT_PLAYER_UNCLAIMING_MINECRAFT_PROFILE_ID_UINDEX = Internal.createUniqueKey(RpkitPlayerUnclaiming.RPKIT_PLAYER_UNCLAIMING, "KEY_rpkit_player_unclaiming_rpkit_player_unclaiming_minecraft_profile_id_uindex", new TableField[] { RpkitPlayerUnclaiming.RPKIT_PLAYER_UNCLAIMING.MINECRAFT_PROFILE_ID }, true);
    }
}
