/*
 * This file is generated by jOOQ.
*/
package com.rpkit.auctions.bukkit.database.jooq.rpkit;


import com.rpkit.auctions.bukkit.database.jooq.rpkit.tables.RpkitAuction;
import com.rpkit.auctions.bukkit.database.jooq.rpkit.tables.RpkitBid;
import com.rpkit.auctions.bukkit.database.jooq.rpkit.tables.records.RpkitAuctionRecord;
import com.rpkit.auctions.bukkit.database.jooq.rpkit.tables.records.RpkitBidRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>rpkit</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RpkitAuctionRecord, Integer> IDENTITY_RPKIT_AUCTION = Identities0.IDENTITY_RPKIT_AUCTION;
    public static final Identity<RpkitBidRecord, Integer> IDENTITY_RPKIT_BID = Identities0.IDENTITY_RPKIT_BID;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RpkitAuctionRecord> KEY_RPKIT_AUCTION_PRIMARY = UniqueKeys0.KEY_RPKIT_AUCTION_PRIMARY;
    public static final UniqueKey<RpkitBidRecord> KEY_RPKIT_BID_PRIMARY = UniqueKeys0.KEY_RPKIT_BID_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<RpkitAuctionRecord, Integer> IDENTITY_RPKIT_AUCTION = createIdentity(RpkitAuction.RPKIT_AUCTION, RpkitAuction.RPKIT_AUCTION.ID);
        public static Identity<RpkitBidRecord, Integer> IDENTITY_RPKIT_BID = createIdentity(RpkitBid.RPKIT_BID, RpkitBid.RPKIT_BID.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<RpkitAuctionRecord> KEY_RPKIT_AUCTION_PRIMARY = createUniqueKey(RpkitAuction.RPKIT_AUCTION, "KEY_rpkit_auction_PRIMARY", RpkitAuction.RPKIT_AUCTION.ID);
        public static final UniqueKey<RpkitBidRecord> KEY_RPKIT_BID_PRIMARY = createUniqueKey(RpkitBid.RPKIT_BID, "KEY_rpkit_bid_PRIMARY", RpkitBid.RPKIT_BID.ID);
    }
}
