/*
 * This file is generated by jOOQ.
 */
package com.rpkit.drinks.bukkit.database.jooq.tables.records;


import com.rpkit.drinks.bukkit.database.jooq.tables.RpkitDrunkenness;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitDrunkennessRecord extends UpdatableRecordImpl<RpkitDrunkennessRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rpkit_drinks.rpkit_drunkenness.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rpkit_drinks.rpkit_drunkenness.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rpkit_drinks.rpkit_drunkenness.drunkenness</code>.
     */
    public void setDrunkenness(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rpkit_drinks.rpkit_drunkenness.drunkenness</code>.
     */
    public Integer getDrunkenness() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RpkitDrunkenness.RPKIT_DRUNKENNESS.CHARACTER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return RpkitDrunkenness.RPKIT_DRUNKENNESS.DRUNKENNESS;
    }

    @Override
    public Integer component1() {
        return getCharacterId();
    }

    @Override
    public Integer component2() {
        return getDrunkenness();
    }

    @Override
    public Integer value1() {
        return getCharacterId();
    }

    @Override
    public Integer value2() {
        return getDrunkenness();
    }

    @Override
    public RpkitDrunkennessRecord value1(Integer value) {
        setCharacterId(value);
        return this;
    }

    @Override
    public RpkitDrunkennessRecord value2(Integer value) {
        setDrunkenness(value);
        return this;
    }

    @Override
    public RpkitDrunkennessRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RpkitDrunkennessRecord
     */
    public RpkitDrunkennessRecord() {
        super(RpkitDrunkenness.RPKIT_DRUNKENNESS);
    }

    /**
     * Create a detached, initialised RpkitDrunkennessRecord
     */
    public RpkitDrunkennessRecord(Integer characterId, Integer drunkenness) {
        super(RpkitDrunkenness.RPKIT_DRUNKENNESS);

        setCharacterId(characterId);
        setDrunkenness(drunkenness);
    }
}
