/*
 * This file is generated by jOOQ.
 */
package com.rpkit.professions.bukkit.database.jooq.rpkit;


import com.rpkit.professions.bukkit.database.jooq.rpkit.tables.RpkitCharacterProfession;
import com.rpkit.professions.bukkit.database.jooq.rpkit.tables.RpkitCharacterProfessionChangeCooldown;
import com.rpkit.professions.bukkit.database.jooq.rpkit.tables.RpkitCharacterProfessionExperience;
import com.rpkit.professions.bukkit.database.jooq.rpkit.tables.RpkitProfessionHidden;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>rpkit</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index RPKIT_CHARACTER_PROFESSION_PRIMARY = Indexes0.RPKIT_CHARACTER_PROFESSION_PRIMARY;
    public static final Index RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN_PRIMARY = Indexes0.RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN_PRIMARY;
    public static final Index RPKIT_CHARACTER_PROFESSION_EXPERIENCE_PRIMARY = Indexes0.RPKIT_CHARACTER_PROFESSION_EXPERIENCE_PRIMARY;
    public static final Index RPKIT_PROFESSION_HIDDEN_PRIMARY = Indexes0.RPKIT_PROFESSION_HIDDEN_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index RPKIT_CHARACTER_PROFESSION_PRIMARY = Internal.createIndex("PRIMARY", RpkitCharacterProfession.RPKIT_CHARACTER_PROFESSION, new OrderField[] { RpkitCharacterProfession.RPKIT_CHARACTER_PROFESSION.ID }, true);
        public static Index RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN_PRIMARY = Internal.createIndex("PRIMARY", RpkitCharacterProfessionChangeCooldown.RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN, new OrderField[] { RpkitCharacterProfessionChangeCooldown.RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN.ID }, true);
        public static Index RPKIT_CHARACTER_PROFESSION_EXPERIENCE_PRIMARY = Internal.createIndex("PRIMARY", RpkitCharacterProfessionExperience.RPKIT_CHARACTER_PROFESSION_EXPERIENCE, new OrderField[] { RpkitCharacterProfessionExperience.RPKIT_CHARACTER_PROFESSION_EXPERIENCE.ID }, true);
        public static Index RPKIT_PROFESSION_HIDDEN_PRIMARY = Internal.createIndex("PRIMARY", RpkitProfessionHidden.RPKIT_PROFESSION_HIDDEN, new OrderField[] { RpkitProfessionHidden.RPKIT_PROFESSION_HIDDEN.ID }, true);
    }
}
