name: rpk-monsters-bukkit
author: alyphen
version: @version@
main: com.rpkit.monsters.bukkit.RPKMonstersBukkit
api-version: '1.16'
depend:
- rpk-core-bukkit
- rpk-player-lib-bukkit
- rpk-character-lib-bukkit
- rpk-economy-lib-bukkit
- rpk-experience-lib-bukkit
- rpk-selection-lib-bukkit
- rpk-stat-lib-bukkit
- rpk-monster-lib-bukkit
commands:
  monsterspawnarea:
    description: Monster spawn area management command
    usage: /<command> [create|remove|addmonster|removemonster]
    aliases: [msa]
permissions:
  rpkit.monsters.command.monsterspawnarea.create:
    description: Allows creating monster spawn areas
    default: op
  rpkit.monsters.command.monsterspawnarea.remove:
    description: Allows removing monster spawn areas
    default: op
  rpkit.monsters.command.monsterspawnarea.addmonster:
    description: Allows adding monsters to spawn areas
    default: op
  rpkit.monsters.command.monsterspawnarea.removemonster:
    description: Allows removing monsters from spawn areas
    default: op