/*
 * This file is generated by jOOQ.
*/
package com.rpkit.classes.bukkit.database.jooq.rpkit.tables;


import com.rpkit.classes.bukkit.database.jooq.rpkit.Indexes;
import com.rpkit.classes.bukkit.database.jooq.rpkit.Keys;
import com.rpkit.classes.bukkit.database.jooq.rpkit.Rpkit;
import com.rpkit.classes.bukkit.database.jooq.rpkit.tables.records.RpkitCharacterClassRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitCharacterClass extends TableImpl<RpkitCharacterClassRecord> {

    private static final long serialVersionUID = -779590619;

    /**
     * The reference instance of <code>rpkit.rpkit_character_class</code>
     */
    public static final RpkitCharacterClass RPKIT_CHARACTER_CLASS = new RpkitCharacterClass();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitCharacterClassRecord> getRecordType() {
        return RpkitCharacterClassRecord.class;
    }

    /**
     * The column <code>rpkit.rpkit_character_class.id</code>.
     */
    public final TableField<RpkitCharacterClassRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>rpkit.rpkit_character_class.character_id</code>.
     */
    public final TableField<RpkitCharacterClassRecord, Integer> CHARACTER_ID = createField("character_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>rpkit.rpkit_character_class.class_name</code>.
     */
    public final TableField<RpkitCharacterClassRecord, String> CLASS_NAME = createField("class_name", org.jooq.impl.SQLDataType.VARCHAR(256), this, "");

    /**
     * Create a <code>rpkit.rpkit_character_class</code> table reference
     */
    public RpkitCharacterClass() {
        this(DSL.name("rpkit_character_class"), null);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_character_class</code> table reference
     */
    public RpkitCharacterClass(String alias) {
        this(DSL.name(alias), RPKIT_CHARACTER_CLASS);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_character_class</code> table reference
     */
    public RpkitCharacterClass(Name alias) {
        this(alias, RPKIT_CHARACTER_CLASS);
    }

    private RpkitCharacterClass(Name alias, Table<RpkitCharacterClassRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitCharacterClass(Name alias, Table<RpkitCharacterClassRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Rpkit.RPKIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RPKIT_CHARACTER_CLASS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RpkitCharacterClassRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RPKIT_CHARACTER_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RpkitCharacterClassRecord> getPrimaryKey() {
        return Keys.KEY_RPKIT_CHARACTER_CLASS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RpkitCharacterClassRecord>> getKeys() {
        return Arrays.<UniqueKey<RpkitCharacterClassRecord>>asList(Keys.KEY_RPKIT_CHARACTER_CLASS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitCharacterClass as(String alias) {
        return new RpkitCharacterClass(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitCharacterClass as(Name alias) {
        return new RpkitCharacterClass(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitCharacterClass rename(String name) {
        return new RpkitCharacterClass(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitCharacterClass rename(Name name) {
        return new RpkitCharacterClass(name, null);
    }
}
