/*
 * This file is generated by jOOQ.
*/
package com.rpkit.permissions.bukkit.database.jooq.rpkit.tables;


import com.rpkit.permissions.bukkit.database.jooq.rpkit.Keys;
import com.rpkit.permissions.bukkit.database.jooq.rpkit.Rpkit;
import com.rpkit.permissions.bukkit.database.jooq.rpkit.tables.records.PlayerGroupRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerGroup extends TableImpl<PlayerGroupRecord> {

    private static final long serialVersionUID = -1779394614;

    /**
     * The reference instance of <code>rpkit.player_group</code>
     */
    public static final PlayerGroup PLAYER_GROUP = new PlayerGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerGroupRecord> getRecordType() {
        return PlayerGroupRecord.class;
    }

    /**
     * The column <code>rpkit.player_group.id</code>.
     */
    public final TableField<PlayerGroupRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit.player_group.player_id</code>.
     */
    public final TableField<PlayerGroupRecord, Integer> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>rpkit.player_group.group_name</code>.
     */
    public final TableField<PlayerGroupRecord, String> GROUP_NAME = createField("group_name", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * Create a <code>rpkit.player_group</code> table reference
     */
    public PlayerGroup() {
        this("player_group", null);
    }

    /**
     * Create an aliased <code>rpkit.player_group</code> table reference
     */
    public PlayerGroup(String alias) {
        this(alias, PLAYER_GROUP);
    }

    private PlayerGroup(String alias, Table<PlayerGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private PlayerGroup(String alias, Table<PlayerGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Rpkit.RPKIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PlayerGroupRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PLAYER_GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PlayerGroupRecord> getPrimaryKey() {
        return Keys.KEY_PLAYER_GROUP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PlayerGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<PlayerGroupRecord>>asList(Keys.KEY_PLAYER_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerGroup as(String alias) {
        return new PlayerGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerGroup rename(String name) {
        return new PlayerGroup(name, null);
    }
}
