/*
 * This file is generated by jOOQ.
*/
package com.rpkit.permissions.bukkit.database.jooq.rpkit.tables;


import com.rpkit.permissions.bukkit.database.jooq.rpkit.Indexes;
import com.rpkit.permissions.bukkit.database.jooq.rpkit.Keys;
import com.rpkit.permissions.bukkit.database.jooq.rpkit.Rpkit;
import com.rpkit.permissions.bukkit.database.jooq.rpkit.tables.records.RpkitCharacterGroupRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitCharacterGroup extends TableImpl<RpkitCharacterGroupRecord> {

    private static final long serialVersionUID = -25698888;

    /**
     * The reference instance of <code>rpkit.rpkit_character_group</code>
     */
    public static final RpkitCharacterGroup RPKIT_CHARACTER_GROUP = new RpkitCharacterGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitCharacterGroupRecord> getRecordType() {
        return RpkitCharacterGroupRecord.class;
    }

    /**
     * The column <code>rpkit.rpkit_character_group.id</code>.
     */
    public final TableField<RpkitCharacterGroupRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>rpkit.rpkit_character_group.character_id</code>.
     */
    public final TableField<RpkitCharacterGroupRecord, Integer> CHARACTER_ID = createField("character_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit.rpkit_character_group.group_name</code>.
     */
    public final TableField<RpkitCharacterGroupRecord, String> GROUP_NAME = createField("group_name", org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * Create a <code>rpkit.rpkit_character_group</code> table reference
     */
    public RpkitCharacterGroup() {
        this(DSL.name("rpkit_character_group"), null);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_character_group</code> table reference
     */
    public RpkitCharacterGroup(String alias) {
        this(DSL.name(alias), RPKIT_CHARACTER_GROUP);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_character_group</code> table reference
     */
    public RpkitCharacterGroup(Name alias) {
        this(alias, RPKIT_CHARACTER_GROUP);
    }

    private RpkitCharacterGroup(Name alias, Table<RpkitCharacterGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitCharacterGroup(Name alias, Table<RpkitCharacterGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Rpkit.RPKIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RPKIT_CHARACTER_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RpkitCharacterGroupRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RPKIT_CHARACTER_GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RpkitCharacterGroupRecord> getPrimaryKey() {
        return Keys.KEY_RPKIT_CHARACTER_GROUP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RpkitCharacterGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<RpkitCharacterGroupRecord>>asList(Keys.KEY_RPKIT_CHARACTER_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitCharacterGroup as(String alias) {
        return new RpkitCharacterGroup(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitCharacterGroup as(Name alias) {
        return new RpkitCharacterGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitCharacterGroup rename(String name) {
        return new RpkitCharacterGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitCharacterGroup rename(Name name) {
        return new RpkitCharacterGroup(name, null);
    }
}
