name: rpk-notifications-bukkit
author: alyphen
version: @version@
main: com.rpkit.notifications.bukkit.RPKNotificationsBukkit
api-version: '1.18'
depend:
- rpk-player-lib-bukkit
- rpk-notification-lib-bukkit
commands:
  notification:
    description: |
      Notification management command
      /notification list - Lists notifications
      /notification view [id] - Views a notification
      /notification dismiss [id] - Dismisses a notification as read
    usage: /<command> [list|view|dismiss]
permissions:
  rpkit.notifications.command.notification.view:
    description: Allows viewing notifications
    default: true
  rpkit.notifications.command.notification.list:
    description: Allows listing notifications
    default: true
  rpkit.notifications.command.notification.dismiss:
    description: Allows dismissing notifications
    default: true