name: rpk-unconsciousness-bukkit
author: alyphen
version: @version@
main: com.rpkit.unconsciousness.bukkit.RPKUnconsciousnessBukkit
depend:
- rpk-core-bukkit
- rpk-player-lib-bukkit
- rpk-character-lib-bukkit
- rpk-unconsciousness-lib-bukkit
api-version: '1.16'
commands:
  wake:
    description: Wakes a player from being unconscious
    usage: /<command> (player)
permissions:
  rpkit.unconsciousness.unconscious.commands:
    description: Allows using commands while unconscious
    default: op