/*
 * This file is generated by jOOQ.
*/
package com.rpkit.players.bukkit.database.jooq.rpkit;


import com.rpkit.players.bukkit.database.jooq.rpkit.tables.*;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.records.*;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>rpkit</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RpkitGithubProfileRecord, Integer> IDENTITY_RPKIT_GITHUB_PROFILE = Identities0.IDENTITY_RPKIT_GITHUB_PROFILE;
    public static final Identity<RpkitIrcProfileRecord, Integer> IDENTITY_RPKIT_IRC_PROFILE = Identities0.IDENTITY_RPKIT_IRC_PROFILE;
    public static final Identity<RpkitMinecraftProfileRecord, Integer> IDENTITY_RPKIT_MINECRAFT_PROFILE = Identities0.IDENTITY_RPKIT_MINECRAFT_PROFILE;
    public static final Identity<RpkitMinecraftProfileTokenRecord, Integer> IDENTITY_RPKIT_MINECRAFT_PROFILE_TOKEN = Identities0.IDENTITY_RPKIT_MINECRAFT_PROFILE_TOKEN;
    public static final Identity<RpkitPlayerRecord, Integer> IDENTITY_RPKIT_PLAYER = Identities0.IDENTITY_RPKIT_PLAYER;
    public static final Identity<RpkitProfileRecord, Integer> IDENTITY_RPKIT_PROFILE = Identities0.IDENTITY_RPKIT_PROFILE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RpkitGithubProfileRecord> KEY_RPKIT_GITHUB_PROFILE_PRIMARY = UniqueKeys0.KEY_RPKIT_GITHUB_PROFILE_PRIMARY;
    public static final UniqueKey<RpkitIrcProfileRecord> KEY_RPKIT_IRC_PROFILE_PRIMARY = UniqueKeys0.KEY_RPKIT_IRC_PROFILE_PRIMARY;
    public static final UniqueKey<RpkitMinecraftProfileRecord> KEY_RPKIT_MINECRAFT_PROFILE_PRIMARY = UniqueKeys0.KEY_RPKIT_MINECRAFT_PROFILE_PRIMARY;
    public static final UniqueKey<RpkitMinecraftProfileTokenRecord> KEY_RPKIT_MINECRAFT_PROFILE_TOKEN_PRIMARY = UniqueKeys0.KEY_RPKIT_MINECRAFT_PROFILE_TOKEN_PRIMARY;
    public static final UniqueKey<RpkitPlayerRecord> KEY_RPKIT_PLAYER_PRIMARY = UniqueKeys0.KEY_RPKIT_PLAYER_PRIMARY;
    public static final UniqueKey<RpkitProfileRecord> KEY_RPKIT_PROFILE_PRIMARY = UniqueKeys0.KEY_RPKIT_PROFILE_PRIMARY;
    public static final UniqueKey<RpkitProfileRecord> KEY_RPKIT_PROFILE_NAME = UniqueKeys0.KEY_RPKIT_PROFILE_NAME;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<RpkitGithubProfileRecord, Integer> IDENTITY_RPKIT_GITHUB_PROFILE = createIdentity(RpkitGithubProfile.RPKIT_GITHUB_PROFILE, RpkitGithubProfile.RPKIT_GITHUB_PROFILE.ID);
        public static Identity<RpkitIrcProfileRecord, Integer> IDENTITY_RPKIT_IRC_PROFILE = createIdentity(RpkitIrcProfile.RPKIT_IRC_PROFILE, RpkitIrcProfile.RPKIT_IRC_PROFILE.ID);
        public static Identity<RpkitMinecraftProfileRecord, Integer> IDENTITY_RPKIT_MINECRAFT_PROFILE = createIdentity(RpkitMinecraftProfile.RPKIT_MINECRAFT_PROFILE, RpkitMinecraftProfile.RPKIT_MINECRAFT_PROFILE.ID);
        public static Identity<RpkitMinecraftProfileTokenRecord, Integer> IDENTITY_RPKIT_MINECRAFT_PROFILE_TOKEN = createIdentity(RpkitMinecraftProfileToken.RPKIT_MINECRAFT_PROFILE_TOKEN, RpkitMinecraftProfileToken.RPKIT_MINECRAFT_PROFILE_TOKEN.ID);
        public static Identity<RpkitPlayerRecord, Integer> IDENTITY_RPKIT_PLAYER = createIdentity(RpkitPlayer.RPKIT_PLAYER, RpkitPlayer.RPKIT_PLAYER.ID);
        public static Identity<RpkitProfileRecord, Integer> IDENTITY_RPKIT_PROFILE = createIdentity(RpkitProfile.RPKIT_PROFILE, RpkitProfile.RPKIT_PROFILE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<RpkitGithubProfileRecord> KEY_RPKIT_GITHUB_PROFILE_PRIMARY = createUniqueKey(RpkitGithubProfile.RPKIT_GITHUB_PROFILE, "KEY_rpkit_github_profile_PRIMARY", RpkitGithubProfile.RPKIT_GITHUB_PROFILE.ID);
        public static final UniqueKey<RpkitIrcProfileRecord> KEY_RPKIT_IRC_PROFILE_PRIMARY = createUniqueKey(RpkitIrcProfile.RPKIT_IRC_PROFILE, "KEY_rpkit_irc_profile_PRIMARY", RpkitIrcProfile.RPKIT_IRC_PROFILE.ID);
        public static final UniqueKey<RpkitMinecraftProfileRecord> KEY_RPKIT_MINECRAFT_PROFILE_PRIMARY = createUniqueKey(RpkitMinecraftProfile.RPKIT_MINECRAFT_PROFILE, "KEY_rpkit_minecraft_profile_PRIMARY", RpkitMinecraftProfile.RPKIT_MINECRAFT_PROFILE.ID);
        public static final UniqueKey<RpkitMinecraftProfileTokenRecord> KEY_RPKIT_MINECRAFT_PROFILE_TOKEN_PRIMARY = createUniqueKey(RpkitMinecraftProfileToken.RPKIT_MINECRAFT_PROFILE_TOKEN, "KEY_rpkit_minecraft_profile_token_PRIMARY", RpkitMinecraftProfileToken.RPKIT_MINECRAFT_PROFILE_TOKEN.ID);
        public static final UniqueKey<RpkitPlayerRecord> KEY_RPKIT_PLAYER_PRIMARY = createUniqueKey(RpkitPlayer.RPKIT_PLAYER, "KEY_rpkit_player_PRIMARY", RpkitPlayer.RPKIT_PLAYER.ID);
        public static final UniqueKey<RpkitProfileRecord> KEY_RPKIT_PROFILE_PRIMARY = createUniqueKey(RpkitProfile.RPKIT_PROFILE, "KEY_rpkit_profile_PRIMARY", RpkitProfile.RPKIT_PROFILE.ID);
        public static final UniqueKey<RpkitProfileRecord> KEY_RPKIT_PROFILE_NAME = createUniqueKey(RpkitProfile.RPKIT_PROFILE, "KEY_rpkit_profile_name", RpkitProfile.RPKIT_PROFILE.NAME);
    }
}
