/*
 * Copyright 2017 Ross Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
*/
package com.rpkit.players.bukkit.database.jooq.rpkit;


import com.rpkit.players.bukkit.database.jooq.DefaultCatalog;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitGithubProfile;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitIrcProfile;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitMinecraftProfile;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitMinecraftProfileLinkRequest;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitMinecraftProfileToken;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitPlayer;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitProfile;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rpkit extends SchemaImpl {

    private static final long serialVersionUID = 1230893882;

    /**
     * The reference instance of <code>rpkit</code>
     */
    public static final Rpkit RPKIT = new Rpkit();

    /**
     * The table <code>rpkit.rpkit_github_profile</code>.
     */
    public final RpkitGithubProfile RPKIT_GITHUB_PROFILE = RpkitGithubProfile.RPKIT_GITHUB_PROFILE;

    /**
     * The table <code>rpkit.rpkit_irc_profile</code>.
     */
    public final RpkitIrcProfile RPKIT_IRC_PROFILE = RpkitIrcProfile.RPKIT_IRC_PROFILE;

    /**
     * The table <code>rpkit.rpkit_minecraft_profile</code>.
     */
    public final RpkitMinecraftProfile RPKIT_MINECRAFT_PROFILE = RpkitMinecraftProfile.RPKIT_MINECRAFT_PROFILE;

    /**
     * The table <code>rpkit.rpkit_minecraft_profile_link_request</code>.
     */
    public final RpkitMinecraftProfileLinkRequest RPKIT_MINECRAFT_PROFILE_LINK_REQUEST = RpkitMinecraftProfileLinkRequest.RPKIT_MINECRAFT_PROFILE_LINK_REQUEST;

    /**
     * The table <code>rpkit.rpkit_minecraft_profile_token</code>.
     */
    public final RpkitMinecraftProfileToken RPKIT_MINECRAFT_PROFILE_TOKEN = RpkitMinecraftProfileToken.RPKIT_MINECRAFT_PROFILE_TOKEN;

    /**
     * The table <code>rpkit.rpkit_player</code>.
     */
    public final RpkitPlayer RPKIT_PLAYER = RpkitPlayer.RPKIT_PLAYER;

    /**
     * The table <code>rpkit.rpkit_profile</code>.
     */
    public final RpkitProfile RPKIT_PROFILE = RpkitProfile.RPKIT_PROFILE;

    /**
     * No further instances allowed
     */
    private Rpkit() {
        super("rpkit", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            RpkitGithubProfile.RPKIT_GITHUB_PROFILE,
            RpkitIrcProfile.RPKIT_IRC_PROFILE,
            RpkitMinecraftProfile.RPKIT_MINECRAFT_PROFILE,
            RpkitMinecraftProfileLinkRequest.RPKIT_MINECRAFT_PROFILE_LINK_REQUEST,
            RpkitMinecraftProfileToken.RPKIT_MINECRAFT_PROFILE_TOKEN,
            RpkitPlayer.RPKIT_PLAYER,
            RpkitProfile.RPKIT_PROFILE);
    }
}
