/*
 * This file is generated by jOOQ.
*/
package com.rpkit.players.bukkit.database.jooq.rpkit;


import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitGithubProfile;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitIrcProfile;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitMinecraftProfile;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitMinecraftProfileLinkRequest;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitMinecraftProfileToken;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitPlayer;
import com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitProfile;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in rpkit
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>rpkit.rpkit_github_profile</code>.
     */
    public static final RpkitGithubProfile RPKIT_GITHUB_PROFILE = com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitGithubProfile.RPKIT_GITHUB_PROFILE;

    /**
     * The table <code>rpkit.rpkit_irc_profile</code>.
     */
    public static final RpkitIrcProfile RPKIT_IRC_PROFILE = com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitIrcProfile.RPKIT_IRC_PROFILE;

    /**
     * The table <code>rpkit.rpkit_minecraft_profile</code>.
     */
    public static final RpkitMinecraftProfile RPKIT_MINECRAFT_PROFILE = com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitMinecraftProfile.RPKIT_MINECRAFT_PROFILE;

    /**
     * The table <code>rpkit.rpkit_minecraft_profile_link_request</code>.
     */
    public static final RpkitMinecraftProfileLinkRequest RPKIT_MINECRAFT_PROFILE_LINK_REQUEST = com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitMinecraftProfileLinkRequest.RPKIT_MINECRAFT_PROFILE_LINK_REQUEST;

    /**
     * The table <code>rpkit.rpkit_minecraft_profile_token</code>.
     */
    public static final RpkitMinecraftProfileToken RPKIT_MINECRAFT_PROFILE_TOKEN = com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitMinecraftProfileToken.RPKIT_MINECRAFT_PROFILE_TOKEN;

    /**
     * The table <code>rpkit.rpkit_player</code>.
     */
    public static final RpkitPlayer RPKIT_PLAYER = com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitPlayer.RPKIT_PLAYER;

    /**
     * The table <code>rpkit.rpkit_profile</code>.
     */
    public static final RpkitProfile RPKIT_PROFILE = com.rpkit.players.bukkit.database.jooq.rpkit.tables.RpkitProfile.RPKIT_PROFILE;
}
