/*
 * This file is generated by jOOQ.
 */
package com.rpkit.shops.bukkit.database.jooq;


import com.rpkit.shops.bukkit.database.jooq.tables.RpkitShopCount;


/**
 * Convenience access to all tables in rpkit_shops.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>rpkit_shops.rpkit_shop_count</code>.
     */
    public static final RpkitShopCount RPKIT_SHOP_COUNT = RpkitShopCount.RPKIT_SHOP_COUNT;
}
