/*
 * This file is generated by jOOQ.
*/
package com.rpkit.payments.bukkit.database.jooq.rpkit.tables;


import com.rpkit.payments.bukkit.database.jooq.rpkit.Keys;
import com.rpkit.payments.bukkit.database.jooq.rpkit.Rpkit;
import com.rpkit.payments.bukkit.database.jooq.rpkit.tables.records.RpkitPaymentGroupRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitPaymentGroup extends TableImpl<RpkitPaymentGroupRecord> {

    private static final long serialVersionUID = 391204981;

    /**
     * The reference instance of <code>rpkit.rpkit_payment_group</code>
     */
    public static final RpkitPaymentGroup RPKIT_PAYMENT_GROUP = new RpkitPaymentGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitPaymentGroupRecord> getRecordType() {
        return RpkitPaymentGroupRecord.class;
    }

    /**
     * The column <code>rpkit.rpkit_payment_group.id</code>.
     */
    public final TableField<RpkitPaymentGroupRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit.rpkit_payment_group.name</code>.
     */
    public final TableField<RpkitPaymentGroupRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * The column <code>rpkit.rpkit_payment_group.amount</code>.
     */
    public final TableField<RpkitPaymentGroupRecord, Integer> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>rpkit.rpkit_payment_group.currency_id</code>.
     */
    public final TableField<RpkitPaymentGroupRecord, Integer> CURRENCY_ID = createField("currency_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>rpkit.rpkit_payment_group.interval</code>.
     */
    public final TableField<RpkitPaymentGroupRecord, Long> INTERVAL = createField("interval", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>rpkit.rpkit_payment_group.last_payment_time</code>.
     */
    public final TableField<RpkitPaymentGroupRecord, Timestamp> LAST_PAYMENT_TIME = createField("last_payment_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>rpkit.rpkit_payment_group.balance</code>.
     */
    public final TableField<RpkitPaymentGroupRecord, Integer> BALANCE = createField("balance", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>rpkit.rpkit_payment_group</code> table reference
     */
    public RpkitPaymentGroup() {
        this("rpkit_payment_group", null);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_payment_group</code> table reference
     */
    public RpkitPaymentGroup(String alias) {
        this(alias, RPKIT_PAYMENT_GROUP);
    }

    private RpkitPaymentGroup(String alias, Table<RpkitPaymentGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitPaymentGroup(String alias, Table<RpkitPaymentGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Rpkit.RPKIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RpkitPaymentGroupRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RPKIT_PAYMENT_GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RpkitPaymentGroupRecord> getPrimaryKey() {
        return Keys.KEY_RPKIT_PAYMENT_GROUP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RpkitPaymentGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<RpkitPaymentGroupRecord>>asList(Keys.KEY_RPKIT_PAYMENT_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitPaymentGroup as(String alias) {
        return new RpkitPaymentGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitPaymentGroup rename(String name) {
        return new RpkitPaymentGroup(name, null);
    }
}
