/*
 * This file is generated by jOOQ.
 */
package com.rpkit.payments.bukkit.database.jooq.tables.records;


import com.rpkit.payments.bukkit.database.jooq.tables.RpkitPaymentGroupOwner;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitPaymentGroupOwnerRecord extends TableRecordImpl<RpkitPaymentGroupOwnerRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>rpkit_payments.rpkit_payment_group_owner.payment_group_id</code>.
     */
    public void setPaymentGroupId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>rpkit_payments.rpkit_payment_group_owner.payment_group_id</code>.
     */
    public Integer getPaymentGroupId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>rpkit_payments.rpkit_payment_group_owner.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>rpkit_payments.rpkit_payment_group_owner.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RpkitPaymentGroupOwner.RPKIT_PAYMENT_GROUP_OWNER.PAYMENT_GROUP_ID;
    }

    @Override
    public Field<Integer> field2() {
        return RpkitPaymentGroupOwner.RPKIT_PAYMENT_GROUP_OWNER.CHARACTER_ID;
    }

    @Override
    public Integer component1() {
        return getPaymentGroupId();
    }

    @Override
    public Integer component2() {
        return getCharacterId();
    }

    @Override
    public Integer value1() {
        return getPaymentGroupId();
    }

    @Override
    public Integer value2() {
        return getCharacterId();
    }

    @Override
    public RpkitPaymentGroupOwnerRecord value1(Integer value) {
        setPaymentGroupId(value);
        return this;
    }

    @Override
    public RpkitPaymentGroupOwnerRecord value2(Integer value) {
        setCharacterId(value);
        return this;
    }

    @Override
    public RpkitPaymentGroupOwnerRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RpkitPaymentGroupOwnerRecord
     */
    public RpkitPaymentGroupOwnerRecord() {
        super(RpkitPaymentGroupOwner.RPKIT_PAYMENT_GROUP_OWNER);
    }

    /**
     * Create a detached, initialised RpkitPaymentGroupOwnerRecord
     */
    public RpkitPaymentGroupOwnerRecord(Integer paymentGroupId, Integer characterId) {
        super(RpkitPaymentGroupOwner.RPKIT_PAYMENT_GROUP_OWNER);

        setPaymentGroupId(paymentGroupId);
        setCharacterId(characterId);
    }
}
