/*
 * Copyright 2020 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.chat.bukkit.database.jooq.tables;


import com.rpkit.chat.bukkit.database.jooq.RpkitChat;
import com.rpkit.chat.bukkit.database.jooq.tables.records.RpkitChatGroupMemberRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitChatGroupMember extends TableImpl<RpkitChatGroupMemberRecord> {

    private static final long serialVersionUID = 2027304631;

    /**
     * The reference instance of <code>rpkit_chat.rpkit_chat_group_member</code>
     */
    public static final RpkitChatGroupMember RPKIT_CHAT_GROUP_MEMBER = new RpkitChatGroupMember();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitChatGroupMemberRecord> getRecordType() {
        return RpkitChatGroupMemberRecord.class;
    }

    /**
     * The column <code>rpkit_chat.rpkit_chat_group_member.chat_group_id</code>.
     */
    public final TableField<RpkitChatGroupMemberRecord, Integer> CHAT_GROUP_ID = createField(DSL.name("chat_group_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit_chat.rpkit_chat_group_member.minecraft_profile_id</code>.
     */
    public final TableField<RpkitChatGroupMemberRecord, Integer> MINECRAFT_PROFILE_ID = createField(DSL.name("minecraft_profile_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>rpkit_chat.rpkit_chat_group_member</code> table reference
     */
    public RpkitChatGroupMember() {
        this(DSL.name("rpkit_chat_group_member"), null);
    }

    /**
     * Create an aliased <code>rpkit_chat.rpkit_chat_group_member</code> table reference
     */
    public RpkitChatGroupMember(String alias) {
        this(DSL.name(alias), RPKIT_CHAT_GROUP_MEMBER);
    }

    /**
     * Create an aliased <code>rpkit_chat.rpkit_chat_group_member</code> table reference
     */
    public RpkitChatGroupMember(Name alias) {
        this(alias, RPKIT_CHAT_GROUP_MEMBER);
    }

    private RpkitChatGroupMember(Name alias, Table<RpkitChatGroupMemberRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitChatGroupMember(Name alias, Table<RpkitChatGroupMemberRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> RpkitChatGroupMember(Table<O> child, ForeignKey<O, RpkitChatGroupMemberRecord> key) {
        super(child, key, RPKIT_CHAT_GROUP_MEMBER);
    }

    @Override
    public Schema getSchema() {
        return RpkitChat.RPKIT_CHAT;
    }

    @Override
    public RpkitChatGroupMember as(String alias) {
        return new RpkitChatGroupMember(DSL.name(alias), this);
    }

    @Override
    public RpkitChatGroupMember as(Name alias) {
        return new RpkitChatGroupMember(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitChatGroupMember rename(String name) {
        return new RpkitChatGroupMember(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitChatGroupMember rename(Name name) {
        return new RpkitChatGroupMember(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
