name: rpk-permissions-bukkit
author: alyphen
version: @version@
main: com.rpkit.permissions.bukkit.RPKPermissionsBukkit
depend:
- rpk-core-bukkit
- rpk-player-lib-bukkit
- rpk-character-lib-bukkit
- rpk-permissions-lib-bukkit
softdepend:
- PlaceholderAPI
api-version: '1.19'
commands:
  group:
    description: Group management command
    usage: /<command> [add|remove|list|view]
  charactergroup:
    description: Character group management command
    usage: /<command> [add|remove|view]
  permissions:
    description: Permissions management commands
    usage: /<command> [reload]
permissions:
  rpkit.permissions.command.group.list:
    description: Allows listing groups
    default: op
  rpkit.permissions.command.group.add:
    description: Allows adding groups to players
    default: op
  rpkit.permissions.command.group.remove:
    description: Allows removing groups from players
    default: op
  rpkit.permissions.command.group.view:
    description: Allows viewing a player's groups
    default: op
  rpkit.permissions.command.charactergroup.add:
    description: Allows adding groups to characters
    default: op
  rpkit.permissions.command.charactergroup.remove:
    description: Allows removing groups from characters
    default: op
  rpkit.permissions.command.charactergroup.view:
    description: Allows viewing a character's groups
    default: op
  rpkit.permissions.command.permissions.reload:
    description: Allows reloading permissions
    default: op