/*
 * This file is generated by jOOQ.
*/
package com.rpkit.characters.bukkit.database.jooq.rpkit;


import com.rpkit.characters.bukkit.database.jooq.rpkit.tables.*;
import com.rpkit.characters.bukkit.database.jooq.rpkit.tables.records.*;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>rpkit</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RpkitCharacterRecord, Integer> IDENTITY_RPKIT_CHARACTER = Identities0.IDENTITY_RPKIT_CHARACTER;
    public static final Identity<RpkitGenderRecord, Integer> IDENTITY_RPKIT_GENDER = Identities0.IDENTITY_RPKIT_GENDER;
    public static final Identity<RpkitNewCharacterCooldownRecord, Integer> IDENTITY_RPKIT_NEW_CHARACTER_COOLDOWN = Identities0.IDENTITY_RPKIT_NEW_CHARACTER_COOLDOWN;
    public static final Identity<RpkitRaceRecord, Integer> IDENTITY_RPKIT_RACE = Identities0.IDENTITY_RPKIT_RACE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PlayerCharacterRecord> KEY_PLAYER_CHARACTER_UK_PLAYER_ID = UniqueKeys0.KEY_PLAYER_CHARACTER_UK_PLAYER_ID;
    public static final UniqueKey<RpkitCharacterRecord> KEY_RPKIT_CHARACTER_PRIMARY = UniqueKeys0.KEY_RPKIT_CHARACTER_PRIMARY;
    public static final UniqueKey<RpkitGenderRecord> KEY_RPKIT_GENDER_PRIMARY = UniqueKeys0.KEY_RPKIT_GENDER_PRIMARY;
    public static final UniqueKey<RpkitNewCharacterCooldownRecord> KEY_RPKIT_NEW_CHARACTER_COOLDOWN_PRIMARY = UniqueKeys0.KEY_RPKIT_NEW_CHARACTER_COOLDOWN_PRIMARY;
    public static final UniqueKey<RpkitRaceRecord> KEY_RPKIT_RACE_PRIMARY = UniqueKeys0.KEY_RPKIT_RACE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<RpkitCharacterRecord, Integer> IDENTITY_RPKIT_CHARACTER = createIdentity(RpkitCharacter.RPKIT_CHARACTER, RpkitCharacter.RPKIT_CHARACTER.ID);
        public static Identity<RpkitGenderRecord, Integer> IDENTITY_RPKIT_GENDER = createIdentity(RpkitGender.RPKIT_GENDER, RpkitGender.RPKIT_GENDER.ID);
        public static Identity<RpkitNewCharacterCooldownRecord, Integer> IDENTITY_RPKIT_NEW_CHARACTER_COOLDOWN = createIdentity(RpkitNewCharacterCooldown.RPKIT_NEW_CHARACTER_COOLDOWN, RpkitNewCharacterCooldown.RPKIT_NEW_CHARACTER_COOLDOWN.ID);
        public static Identity<RpkitRaceRecord, Integer> IDENTITY_RPKIT_RACE = createIdentity(RpkitRace.RPKIT_RACE, RpkitRace.RPKIT_RACE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<PlayerCharacterRecord> KEY_PLAYER_CHARACTER_UK_PLAYER_ID = createUniqueKey(PlayerCharacter.PLAYER_CHARACTER, "KEY_player_character_uk_player_id", PlayerCharacter.PLAYER_CHARACTER.PLAYER_ID);
        public static final UniqueKey<RpkitCharacterRecord> KEY_RPKIT_CHARACTER_PRIMARY = createUniqueKey(RpkitCharacter.RPKIT_CHARACTER, "KEY_rpkit_character_PRIMARY", RpkitCharacter.RPKIT_CHARACTER.ID);
        public static final UniqueKey<RpkitGenderRecord> KEY_RPKIT_GENDER_PRIMARY = createUniqueKey(RpkitGender.RPKIT_GENDER, "KEY_rpkit_gender_PRIMARY", RpkitGender.RPKIT_GENDER.ID);
        public static final UniqueKey<RpkitNewCharacterCooldownRecord> KEY_RPKIT_NEW_CHARACTER_COOLDOWN_PRIMARY = createUniqueKey(RpkitNewCharacterCooldown.RPKIT_NEW_CHARACTER_COOLDOWN, "KEY_rpkit_new_character_cooldown_PRIMARY", RpkitNewCharacterCooldown.RPKIT_NEW_CHARACTER_COOLDOWN.ID);
        public static final UniqueKey<RpkitRaceRecord> KEY_RPKIT_RACE_PRIMARY = createUniqueKey(RpkitRace.RPKIT_RACE, "KEY_rpkit_race_PRIMARY", RpkitRace.RPKIT_RACE.ID);
    }
}
