/*
 * This file is generated by jOOQ.
*/
package com.rpkit.locks.bukkit.database.jooq.rpkit.tables;


import com.rpkit.locks.bukkit.database.jooq.rpkit.Keys;
import com.rpkit.locks.bukkit.database.jooq.rpkit.Rpkit;
import com.rpkit.locks.bukkit.database.jooq.rpkit.tables.records.RpkitPlayerUnclaimingRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitPlayerUnclaiming extends TableImpl<RpkitPlayerUnclaimingRecord> {

    private static final long serialVersionUID = -654862335;

    /**
     * The reference instance of <code>rpkit.rpkit_player_unclaiming</code>
     */
    public static final RpkitPlayerUnclaiming RPKIT_PLAYER_UNCLAIMING = new RpkitPlayerUnclaiming();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitPlayerUnclaimingRecord> getRecordType() {
        return RpkitPlayerUnclaimingRecord.class;
    }

    /**
     * The column <code>rpkit.rpkit_player_unclaiming.id</code>.
     */
    public final TableField<RpkitPlayerUnclaimingRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit.rpkit_player_unclaiming.minecraft_profile_id</code>.
     */
    public final TableField<RpkitPlayerUnclaimingRecord, Integer> MINECRAFT_PROFILE_ID = createField("minecraft_profile_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>rpkit.rpkit_player_unclaiming</code> table reference
     */
    public RpkitPlayerUnclaiming() {
        this("rpkit_player_unclaiming", null);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_player_unclaiming</code> table reference
     */
    public RpkitPlayerUnclaiming(String alias) {
        this(alias, RPKIT_PLAYER_UNCLAIMING);
    }

    private RpkitPlayerUnclaiming(String alias, Table<RpkitPlayerUnclaimingRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitPlayerUnclaiming(String alias, Table<RpkitPlayerUnclaimingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Rpkit.RPKIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RpkitPlayerUnclaimingRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RPKIT_PLAYER_UNCLAIMING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RpkitPlayerUnclaimingRecord> getPrimaryKey() {
        return Keys.KEY_RPKIT_PLAYER_UNCLAIMING_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RpkitPlayerUnclaimingRecord>> getKeys() {
        return Arrays.<UniqueKey<RpkitPlayerUnclaimingRecord>>asList(Keys.KEY_RPKIT_PLAYER_UNCLAIMING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitPlayerUnclaiming as(String alias) {
        return new RpkitPlayerUnclaiming(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitPlayerUnclaiming rename(String name) {
        return new RpkitPlayerUnclaiming(name, null);
    }
}
