/*
 * This file is generated by jOOQ.
 */
package com.rpkit.craftingskill.bukkit.database.jooq.rpkit;


import com.rpkit.craftingskill.bukkit.database.jooq.rpkit.tables.RpkitCraftingExperience;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>rpkit</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index RPKIT_CRAFTING_EXPERIENCE_PRIMARY = Indexes0.RPKIT_CRAFTING_EXPERIENCE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index RPKIT_CRAFTING_EXPERIENCE_PRIMARY = Internal.createIndex("PRIMARY", RpkitCraftingExperience.RPKIT_CRAFTING_EXPERIENCE, new OrderField[] { RpkitCraftingExperience.RPKIT_CRAFTING_EXPERIENCE.ID }, true);
    }
}
