/*
 * Copyright 2020 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.skills.bukkit.database.jooq.tables;


import com.rpkit.skills.bukkit.database.jooq.Keys;
import com.rpkit.skills.bukkit.database.jooq.RpkitSkills;
import com.rpkit.skills.bukkit.database.jooq.tables.records.RpkitSkillBindingRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitSkillBinding extends TableImpl<RpkitSkillBindingRecord> {

    private static final long serialVersionUID = 665524546;

    /**
     * The reference instance of <code>rpkit_skills.rpkit_skill_binding</code>
     */
    public static final RpkitSkillBinding RPKIT_SKILL_BINDING = new RpkitSkillBinding();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitSkillBindingRecord> getRecordType() {
        return RpkitSkillBindingRecord.class;
    }

    /**
     * The column <code>rpkit_skills.rpkit_skill_binding.id</code>.
     */
    public final TableField<RpkitSkillBindingRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>rpkit_skills.rpkit_skill_binding.character_id</code>.
     */
    public final TableField<RpkitSkillBindingRecord, Integer> CHARACTER_ID = createField(DSL.name("character_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit_skills.rpkit_skill_binding.item</code>.
     */
    public final TableField<RpkitSkillBindingRecord, byte[]> ITEM = createField(DSL.name("item"), org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>rpkit_skills.rpkit_skill_binding.skill_name</code>.
     */
    public final TableField<RpkitSkillBindingRecord, String> SKILL_NAME = createField(DSL.name("skill_name"), org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * Create a <code>rpkit_skills.rpkit_skill_binding</code> table reference
     */
    public RpkitSkillBinding() {
        this(DSL.name("rpkit_skill_binding"), null);
    }

    /**
     * Create an aliased <code>rpkit_skills.rpkit_skill_binding</code> table reference
     */
    public RpkitSkillBinding(String alias) {
        this(DSL.name(alias), RPKIT_SKILL_BINDING);
    }

    /**
     * Create an aliased <code>rpkit_skills.rpkit_skill_binding</code> table reference
     */
    public RpkitSkillBinding(Name alias) {
        this(alias, RPKIT_SKILL_BINDING);
    }

    private RpkitSkillBinding(Name alias, Table<RpkitSkillBindingRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitSkillBinding(Name alias, Table<RpkitSkillBindingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> RpkitSkillBinding(Table<O> child, ForeignKey<O, RpkitSkillBindingRecord> key) {
        super(child, key, RPKIT_SKILL_BINDING);
    }

    @Override
    public Schema getSchema() {
        return RpkitSkills.RPKIT_SKILLS;
    }

    @Override
    public Identity<RpkitSkillBindingRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RPKIT_SKILL_BINDING;
    }

    @Override
    public UniqueKey<RpkitSkillBindingRecord> getPrimaryKey() {
        return Keys.KEY_RPKIT_SKILL_BINDING_PRIMARY;
    }

    @Override
    public List<UniqueKey<RpkitSkillBindingRecord>> getKeys() {
        return Arrays.<UniqueKey<RpkitSkillBindingRecord>>asList(Keys.KEY_RPKIT_SKILL_BINDING_PRIMARY);
    }

    @Override
    public RpkitSkillBinding as(String alias) {
        return new RpkitSkillBinding(DSL.name(alias), this);
    }

    @Override
    public RpkitSkillBinding as(Name alias) {
        return new RpkitSkillBinding(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitSkillBinding rename(String name) {
        return new RpkitSkillBinding(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitSkillBinding rename(Name name) {
        return new RpkitSkillBinding(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, byte[], String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
