/*
 * This file is generated by jOOQ.
*/
package com.rpkit.moderation.bukkit.database.jooq.rpkit.tables;


import com.rpkit.moderation.bukkit.database.jooq.rpkit.Indexes;
import com.rpkit.moderation.bukkit.database.jooq.rpkit.Keys;
import com.rpkit.moderation.bukkit.database.jooq.rpkit.Rpkit;
import com.rpkit.moderation.bukkit.database.jooq.rpkit.tables.records.RpkitWarningRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitWarning extends TableImpl<RpkitWarningRecord> {

    private static final long serialVersionUID = 1794590494;

    /**
     * The reference instance of <code>rpkit.rpkit_warning</code>
     */
    public static final RpkitWarning RPKIT_WARNING = new RpkitWarning();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitWarningRecord> getRecordType() {
        return RpkitWarningRecord.class;
    }

    /**
     * The column <code>rpkit.rpkit_warning.id</code>.
     */
    public final TableField<RpkitWarningRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>rpkit.rpkit_warning.reason</code>.
     */
    public final TableField<RpkitWarningRecord, String> REASON = createField("reason", org.jooq.impl.SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>rpkit.rpkit_warning.profile_id</code>.
     */
    public final TableField<RpkitWarningRecord, Integer> PROFILE_ID = createField("profile_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit.rpkit_warning.issuer_id</code>.
     */
    public final TableField<RpkitWarningRecord, Integer> ISSUER_ID = createField("issuer_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit.rpkit_warning.time</code>.
     */
    public final TableField<RpkitWarningRecord, Timestamp> TIME = createField("time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>rpkit.rpkit_warning</code> table reference
     */
    public RpkitWarning() {
        this(DSL.name("rpkit_warning"), null);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_warning</code> table reference
     */
    public RpkitWarning(String alias) {
        this(DSL.name(alias), RPKIT_WARNING);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_warning</code> table reference
     */
    public RpkitWarning(Name alias) {
        this(alias, RPKIT_WARNING);
    }

    private RpkitWarning(Name alias, Table<RpkitWarningRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitWarning(Name alias, Table<RpkitWarningRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Rpkit.RPKIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RPKIT_WARNING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RpkitWarningRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RPKIT_WARNING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RpkitWarningRecord> getPrimaryKey() {
        return Keys.KEY_RPKIT_WARNING_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RpkitWarningRecord>> getKeys() {
        return Arrays.<UniqueKey<RpkitWarningRecord>>asList(Keys.KEY_RPKIT_WARNING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitWarning as(String alias) {
        return new RpkitWarning(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitWarning as(Name alias) {
        return new RpkitWarning(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitWarning rename(String name) {
        return new RpkitWarning(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitWarning rename(Name name) {
        return new RpkitWarning(name, null);
    }
}
