/*
 * This file is generated by jOOQ.
*/
package com.rpkit.moderation.bukkit.database.jooq.rpkit.tables;


import com.rpkit.moderation.bukkit.database.jooq.rpkit.Indexes;
import com.rpkit.moderation.bukkit.database.jooq.rpkit.Keys;
import com.rpkit.moderation.bukkit.database.jooq.rpkit.Rpkit;
import com.rpkit.moderation.bukkit.database.jooq.rpkit.tables.records.RpkitVanishStateRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitVanishState extends TableImpl<RpkitVanishStateRecord> {

    private static final long serialVersionUID = 848841692;

    /**
     * The reference instance of <code>rpkit.rpkit_vanish_state</code>
     */
    public static final RpkitVanishState RPKIT_VANISH_STATE = new RpkitVanishState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitVanishStateRecord> getRecordType() {
        return RpkitVanishStateRecord.class;
    }

    /**
     * The column <code>rpkit.rpkit_vanish_state.id</code>.
     */
    public final TableField<RpkitVanishStateRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>rpkit.rpkit_vanish_state.minecraft_profile_id</code>.
     */
    public final TableField<RpkitVanishStateRecord, Integer> MINECRAFT_PROFILE_ID = createField("minecraft_profile_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit.rpkit_vanish_state.vanished</code>.
     */
    public final TableField<RpkitVanishStateRecord, Byte> VANISHED = createField("vanished", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * Create a <code>rpkit.rpkit_vanish_state</code> table reference
     */
    public RpkitVanishState() {
        this(DSL.name("rpkit_vanish_state"), null);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_vanish_state</code> table reference
     */
    public RpkitVanishState(String alias) {
        this(DSL.name(alias), RPKIT_VANISH_STATE);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_vanish_state</code> table reference
     */
    public RpkitVanishState(Name alias) {
        this(alias, RPKIT_VANISH_STATE);
    }

    private RpkitVanishState(Name alias, Table<RpkitVanishStateRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitVanishState(Name alias, Table<RpkitVanishStateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Rpkit.RPKIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RPKIT_VANISH_STATE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RpkitVanishStateRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RPKIT_VANISH_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RpkitVanishStateRecord> getPrimaryKey() {
        return Keys.KEY_RPKIT_VANISH_STATE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RpkitVanishStateRecord>> getKeys() {
        return Arrays.<UniqueKey<RpkitVanishStateRecord>>asList(Keys.KEY_RPKIT_VANISH_STATE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitVanishState as(String alias) {
        return new RpkitVanishState(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitVanishState as(Name alias) {
        return new RpkitVanishState(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitVanishState rename(String name) {
        return new RpkitVanishState(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitVanishState rename(Name name) {
        return new RpkitVanishState(name, null);
    }
}
