item-qualities:
  poor:
    lore:
    - '&fQuality: &7Poor'
    durability-modifier: 0.25
    applicable-items:
    - APPLE
    - MUSHROOM_STEW
    - BREAD
    - PORKCHOP
    - COOKED_PORKCHOP
    - GOLDEN_APPLE
    - ENCHANTED_GOLDEN_APPLE
    - COD
    - SALMON
    - TROPICAL_FISH
    - PUFFERFISH
    - COOKED_COD
    - COOKED_SALMON
    - COOKIE
    - MELON_SLICE
    - DRIED_KELP
    - BEEF
    - COOKED_BEEF
    - CHICKEN
    - COOKED_CHICKEN
    - ROTTEN_FLESH
    - SPIDER_EYE
    - CARROT
    - POTATO
    - BAKED_POTATO
    - POISONOUS_POTATO
    - GOLDEN_CARROT
    - PUMPKIN_PIE
    - RABBIT
    - COOKED_RABBIT
    - RABBIT_STEW
    - MUTTON
    - COOKED_MUTTON
    - CHORUS_FRUIT
    - BEETROOT
    - BEETROOT_SOUP
    - SUSPICIOUS_STEW
    - SWEET_BERRIES
    - HONEY_BOTTLE
    - DIAMOND_AXE
    - DIAMOND_BOOTS
    - DIAMOND_CHESTPLATE
    - DIAMOND_HELMET
    - DIAMOND_HOE
    - DIAMOND_HORSE_ARMOR
    - DIAMOND_LEGGINGS
    - DIAMOND_PICKAXE
    - DIAMOND_SHOVEL
    - DIAMOND_SWORD
    - GOLDEN_AXE
    - GOLDEN_BOOTS
    - GOLDEN_CHESTPLATE
    - GOLDEN_HELMET
    - GOLDEN_HOE
    - GOLDEN_HORSE_ARMOR
    - GOLDEN_LEGGINGS
    - GOLDEN_PICKAXE
    - GOLDEN_SHOVEL
    - GOLDEN_SWORD
    - IRON_AXE
    - IRON_BOOTS
    - IRON_CHESTPLATE
    - IRON_HELMET
    - IRON_HOE
    - IRON_HORSE_ARMOR
    - IRON_LEGGINGS
    - IRON_PICKAXE
    - IRON_SHOVEL
    - IRON_SWORD
    - NETHERITE_AXE
    - NETHERITE_BOOTS
    - NETHERITE_CHESTPLATE
    - NETHERITE_HELMET
    - NETHERITE_HOE
    - NETHERITE_LEGGINGS
    - NETHERITE_PICKAXE
    - NETHERITE_SHOVEL
    - NETHERITE_SWORD
    - STONE_AXE
    - STONE_HOE
    - STONE_PICKAXE
    - STONE_SHOVEL
    - STONE_SWORD
    - WOODEN_AXE
    - WOODEN_HOE
    - WOODEN_PICKAXE
    - WOODEN_SHOVEL
    - WOODEN_SWORD
    - LEATHER_BOOTS
    - LEATHER_CHESTPLATE
    - LEATHER_HELMET
    - LEATHER_HORSE_ARMOR
    - LEATHER_LEGGINGS
    - CHAINMAIL_BOOTS
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_HELMET
    - CHAINMAIL_LEGGINGS
    - TURTLE_HELMET
    - FLINT_AND_STEEL
    - SHEARS
    - FISHING_ROD
  common:
    lore:
    - '&fQuality: &fCommon'
    durability-modifier: 0.5
    applicable-items:
    - APPLE
    - MUSHROOM_STEW
    - BREAD
    - PORKCHOP
    - COOKED_PORKCHOP
    - GOLDEN_APPLE
    - ENCHANTED_GOLDEN_APPLE
    - COD
    - SALMON
    - TROPICAL_FISH
    - PUFFERFISH
    - COOKED_COD
    - COOKED_SALMON
    - COOKIE
    - MELON_SLICE
    - DRIED_KELP
    - BEEF
    - COOKED_BEEF
    - CHICKEN
    - COOKED_CHICKEN
    - ROTTEN_FLESH
    - SPIDER_EYE
    - CARROT
    - POTATO
    - BAKED_POTATO
    - POISONOUS_POTATO
    - GOLDEN_CARROT
    - PUMPKIN_PIE
    - RABBIT
    - COOKED_RABBIT
    - RABBIT_STEW
    - MUTTON
    - COOKED_MUTTON
    - CHORUS_FRUIT
    - BEETROOT
    - BEETROOT_SOUP
    - SUSPICIOUS_STEW
    - SWEET_BERRIES
    - HONEY_BOTTLE
    - DIAMOND_AXE
    - DIAMOND_BOOTS
    - DIAMOND_CHESTPLATE
    - DIAMOND_HELMET
    - DIAMOND_HOE
    - DIAMOND_HORSE_ARMOR
    - DIAMOND_LEGGINGS
    - DIAMOND_PICKAXE
    - DIAMOND_SHOVEL
    - DIAMOND_SWORD
    - GOLDEN_AXE
    - GOLDEN_BOOTS
    - GOLDEN_CHESTPLATE
    - GOLDEN_HELMET
    - GOLDEN_HOE
    - GOLDEN_HORSE_ARMOR
    - GOLDEN_LEGGINGS
    - GOLDEN_PICKAXE
    - GOLDEN_SHOVEL
    - GOLDEN_SWORD
    - IRON_AXE
    - IRON_BOOTS
    - IRON_CHESTPLATE
    - IRON_HELMET
    - IRON_HOE
    - IRON_HORSE_ARMOR
    - IRON_LEGGINGS
    - IRON_PICKAXE
    - IRON_SHOVEL
    - IRON_SWORD
    - NETHERITE_AXE
    - NETHERITE_BOOTS
    - NETHERITE_CHESTPLATE
    - NETHERITE_HELMET
    - NETHERITE_HOE
    - NETHERITE_LEGGINGS
    - NETHERITE_PICKAXE
    - NETHERITE_SHOVEL
    - NETHERITE_SWORD
    - STONE_AXE
    - STONE_HOE
    - STONE_PICKAXE
    - STONE_SHOVEL
    - STONE_SWORD
    - WOODEN_AXE
    - WOODEN_HOE
    - WOODEN_PICKAXE
    - WOODEN_SHOVEL
    - WOODEN_SWORD
    - LEATHER_BOOTS
    - LEATHER_CHESTPLATE
    - LEATHER_HELMET
    - LEATHER_HORSE_ARMOR
    - LEATHER_LEGGINGS
    - CHAINMAIL_BOOTS
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_HELMET
    - CHAINMAIL_LEGGINGS
    - TURTLE_HELMET
    - FLINT_AND_STEEL
    - SHEARS
    - FISHING_ROD
  uncommon:
    lore:
    - '&fQuality: &aUncommon'
    durability-modifier: 0.75
    applicable-items:
    - APPLE
    - MUSHROOM_STEW
    - BREAD
    - PORKCHOP
    - COOKED_PORKCHOP
    - GOLDEN_APPLE
    - ENCHANTED_GOLDEN_APPLE
    - COD
    - SALMON
    - TROPICAL_FISH
    - PUFFERFISH
    - COOKED_COD
    - COOKED_SALMON
    - COOKIE
    - MELON_SLICE
    - DRIED_KELP
    - BEEF
    - COOKED_BEEF
    - CHICKEN
    - COOKED_CHICKEN
    - ROTTEN_FLESH
    - SPIDER_EYE
    - CARROT
    - POTATO
    - BAKED_POTATO
    - POISONOUS_POTATO
    - GOLDEN_CARROT
    - PUMPKIN_PIE
    - RABBIT
    - COOKED_RABBIT
    - RABBIT_STEW
    - MUTTON
    - COOKED_MUTTON
    - CHORUS_FRUIT
    - BEETROOT
    - BEETROOT_SOUP
    - SUSPICIOUS_STEW
    - SWEET_BERRIES
    - HONEY_BOTTLE
    - DIAMOND_AXE
    - DIAMOND_BOOTS
    - DIAMOND_CHESTPLATE
    - DIAMOND_HELMET
    - DIAMOND_HOE
    - DIAMOND_HORSE_ARMOR
    - DIAMOND_LEGGINGS
    - DIAMOND_PICKAXE
    - DIAMOND_SHOVEL
    - DIAMOND_SWORD
    - GOLDEN_AXE
    - GOLDEN_BOOTS
    - GOLDEN_CHESTPLATE
    - GOLDEN_HELMET
    - GOLDEN_HOE
    - GOLDEN_HORSE_ARMOR
    - GOLDEN_LEGGINGS
    - GOLDEN_PICKAXE
    - GOLDEN_SHOVEL
    - GOLDEN_SWORD
    - IRON_AXE
    - IRON_BOOTS
    - IRON_CHESTPLATE
    - IRON_HELMET
    - IRON_HOE
    - IRON_HORSE_ARMOR
    - IRON_LEGGINGS
    - IRON_PICKAXE
    - IRON_SHOVEL
    - IRON_SWORD
    - NETHERITE_AXE
    - NETHERITE_BOOTS
    - NETHERITE_CHESTPLATE
    - NETHERITE_HELMET
    - NETHERITE_HOE
    - NETHERITE_LEGGINGS
    - NETHERITE_PICKAXE
    - NETHERITE_SHOVEL
    - NETHERITE_SWORD
    - STONE_AXE
    - STONE_HOE
    - STONE_PICKAXE
    - STONE_SHOVEL
    - STONE_SWORD
    - WOODEN_AXE
    - WOODEN_HOE
    - WOODEN_PICKAXE
    - WOODEN_SHOVEL
    - WOODEN_SWORD
    - LEATHER_BOOTS
    - LEATHER_CHESTPLATE
    - LEATHER_HELMET
    - LEATHER_HORSE_ARMOR
    - LEATHER_LEGGINGS
    - CHAINMAIL_BOOTS
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_HELMET
    - CHAINMAIL_LEGGINGS
    - TURTLE_HELMET
    - FLINT_AND_STEEL
    - SHEARS
    - FISHING_ROD
  rare:
    lore:
    - '&fQuality: &9Rare'
    durability-modifier: 1
    applicable-items:
    - APPLE
    - MUSHROOM_STEW
    - BREAD
    - PORKCHOP
    - COOKED_PORKCHOP
    - GOLDEN_APPLE
    - ENCHANTED_GOLDEN_APPLE
    - COD
    - SALMON
    - TROPICAL_FISH
    - PUFFERFISH
    - COOKED_COD
    - COOKED_SALMON
    - COOKIE
    - MELON_SLICE
    - DRIED_KELP
    - BEEF
    - COOKED_BEEF
    - CHICKEN
    - COOKED_CHICKEN
    - ROTTEN_FLESH
    - SPIDER_EYE
    - CARROT
    - POTATO
    - BAKED_POTATO
    - POISONOUS_POTATO
    - GOLDEN_CARROT
    - PUMPKIN_PIE
    - RABBIT
    - COOKED_RABBIT
    - RABBIT_STEW
    - MUTTON
    - COOKED_MUTTON
    - CHORUS_FRUIT
    - BEETROOT
    - BEETROOT_SOUP
    - SUSPICIOUS_STEW
    - SWEET_BERRIES
    - HONEY_BOTTLE
    - DIAMOND_AXE
    - DIAMOND_BOOTS
    - DIAMOND_CHESTPLATE
    - DIAMOND_HELMET
    - DIAMOND_HOE
    - DIAMOND_HORSE_ARMOR
    - DIAMOND_LEGGINGS
    - DIAMOND_PICKAXE
    - DIAMOND_SHOVEL
    - DIAMOND_SWORD
    - GOLDEN_AXE
    - GOLDEN_BOOTS
    - GOLDEN_CHESTPLATE
    - GOLDEN_HELMET
    - GOLDEN_HOE
    - GOLDEN_HORSE_ARMOR
    - GOLDEN_LEGGINGS
    - GOLDEN_PICKAXE
    - GOLDEN_SHOVEL
    - GOLDEN_SWORD
    - IRON_AXE
    - IRON_BOOTS
    - IRON_CHESTPLATE
    - IRON_HELMET
    - IRON_HOE
    - IRON_HORSE_ARMOR
    - IRON_LEGGINGS
    - IRON_PICKAXE
    - IRON_SHOVEL
    - IRON_SWORD
    - NETHERITE_AXE
    - NETHERITE_BOOTS
    - NETHERITE_CHESTPLATE
    - NETHERITE_HELMET
    - NETHERITE_HOE
    - NETHERITE_LEGGINGS
    - NETHERITE_PICKAXE
    - NETHERITE_SHOVEL
    - NETHERITE_SWORD
    - STONE_AXE
    - STONE_HOE
    - STONE_PICKAXE
    - STONE_SHOVEL
    - STONE_SWORD
    - WOODEN_AXE
    - WOODEN_HOE
    - WOODEN_PICKAXE
    - WOODEN_SHOVEL
    - WOODEN_SWORD
    - LEATHER_BOOTS
    - LEATHER_CHESTPLATE
    - LEATHER_HELMET
    - LEATHER_HORSE_ARMOR
    - LEATHER_LEGGINGS
    - CHAINMAIL_BOOTS
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_HELMET
    - CHAINMAIL_LEGGINGS
    - TURTLE_HELMET
    - FLINT_AND_STEEL
    - SHEARS
    - FISHING_ROD
  epic:
    lore:
    - '&fQuality: &5Epic'
    durability-modifier: 1.25
    applicable-items:
    - APPLE
    - MUSHROOM_STEW
    - BREAD
    - PORKCHOP
    - COOKED_PORKCHOP
    - GOLDEN_APPLE
    - ENCHANTED_GOLDEN_APPLE
    - COD
    - SALMON
    - TROPICAL_FISH
    - PUFFERFISH
    - COOKED_COD
    - COOKED_SALMON
    - COOKIE
    - MELON_SLICE
    - DRIED_KELP
    - BEEF
    - COOKED_BEEF
    - CHICKEN
    - COOKED_CHICKEN
    - ROTTEN_FLESH
    - SPIDER_EYE
    - CARROT
    - POTATO
    - BAKED_POTATO
    - POISONOUS_POTATO
    - GOLDEN_CARROT
    - PUMPKIN_PIE
    - RABBIT
    - COOKED_RABBIT
    - RABBIT_STEW
    - MUTTON
    - COOKED_MUTTON
    - CHORUS_FRUIT
    - BEETROOT
    - BEETROOT_SOUP
    - SUSPICIOUS_STEW
    - SWEET_BERRIES
    - HONEY_BOTTLE
    - DIAMOND_AXE
    - DIAMOND_BOOTS
    - DIAMOND_CHESTPLATE
    - DIAMOND_HELMET
    - DIAMOND_HOE
    - DIAMOND_HORSE_ARMOR
    - DIAMOND_LEGGINGS
    - DIAMOND_PICKAXE
    - DIAMOND_SHOVEL
    - DIAMOND_SWORD
    - GOLDEN_AXE
    - GOLDEN_BOOTS
    - GOLDEN_CHESTPLATE
    - GOLDEN_HELMET
    - GOLDEN_HOE
    - GOLDEN_HORSE_ARMOR
    - GOLDEN_LEGGINGS
    - GOLDEN_PICKAXE
    - GOLDEN_SHOVEL
    - GOLDEN_SWORD
    - IRON_AXE
    - IRON_BOOTS
    - IRON_CHESTPLATE
    - IRON_HELMET
    - IRON_HOE
    - IRON_HORSE_ARMOR
    - IRON_LEGGINGS
    - IRON_PICKAXE
    - IRON_SHOVEL
    - IRON_SWORD
    - NETHERITE_AXE
    - NETHERITE_BOOTS
    - NETHERITE_CHESTPLATE
    - NETHERITE_HELMET
    - NETHERITE_HOE
    - NETHERITE_LEGGINGS
    - NETHERITE_PICKAXE
    - NETHERITE_SHOVEL
    - NETHERITE_SWORD
    - STONE_AXE
    - STONE_HOE
    - STONE_PICKAXE
    - STONE_SHOVEL
    - STONE_SWORD
    - WOODEN_AXE
    - WOODEN_HOE
    - WOODEN_PICKAXE
    - WOODEN_SHOVEL
    - WOODEN_SWORD
    - LEATHER_BOOTS
    - LEATHER_CHESTPLATE
    - LEATHER_HELMET
    - LEATHER_HORSE_ARMOR
    - LEATHER_LEGGINGS
    - CHAINMAIL_BOOTS
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_HELMET
    - CHAINMAIL_LEGGINGS
    - TURTLE_HELMET
    - FLINT_AND_STEEL
    - SHEARS
    - FISHING_ROD
  legendary:
    lore:
    - '&fQuality: &6Legendary'
    durability-modifier: 1.75
    applicable-items:
    - APPLE
    - MUSHROOM_STEW
    - BREAD
    - PORKCHOP
    - COOKED_PORKCHOP
    - GOLDEN_APPLE
    - ENCHANTED_GOLDEN_APPLE
    - COD
    - SALMON
    - TROPICAL_FISH
    - PUFFERFISH
    - COOKED_COD
    - COOKED_SALMON
    - COOKIE
    - MELON_SLICE
    - DRIED_KELP
    - BEEF
    - COOKED_BEEF
    - CHICKEN
    - COOKED_CHICKEN
    - ROTTEN_FLESH
    - SPIDER_EYE
    - CARROT
    - POTATO
    - BAKED_POTATO
    - POISONOUS_POTATO
    - GOLDEN_CARROT
    - PUMPKIN_PIE
    - RABBIT
    - COOKED_RABBIT
    - RABBIT_STEW
    - MUTTON
    - COOKED_MUTTON
    - CHORUS_FRUIT
    - BEETROOT
    - BEETROOT_SOUP
    - SUSPICIOUS_STEW
    - SWEET_BERRIES
    - HONEY_BOTTLE
    - DIAMOND_AXE
    - DIAMOND_BOOTS
    - DIAMOND_CHESTPLATE
    - DIAMOND_HELMET
    - DIAMOND_HOE
    - DIAMOND_HORSE_ARMOR
    - DIAMOND_LEGGINGS
    - DIAMOND_PICKAXE
    - DIAMOND_SHOVEL
    - DIAMOND_SWORD
    - GOLDEN_AXE
    - GOLDEN_BOOTS
    - GOLDEN_CHESTPLATE
    - GOLDEN_HELMET
    - GOLDEN_HOE
    - GOLDEN_HORSE_ARMOR
    - GOLDEN_LEGGINGS
    - GOLDEN_PICKAXE
    - GOLDEN_SHOVEL
    - GOLDEN_SWORD
    - IRON_AXE
    - IRON_BOOTS
    - IRON_CHESTPLATE
    - IRON_HELMET
    - IRON_HOE
    - IRON_HORSE_ARMOR
    - IRON_LEGGINGS
    - IRON_PICKAXE
    - IRON_SHOVEL
    - IRON_SWORD
    - NETHERITE_AXE
    - NETHERITE_BOOTS
    - NETHERITE_CHESTPLATE
    - NETHERITE_HELMET
    - NETHERITE_HOE
    - NETHERITE_LEGGINGS
    - NETHERITE_PICKAXE
    - NETHERITE_SHOVEL
    - NETHERITE_SWORD
    - STONE_AXE
    - STONE_HOE
    - STONE_PICKAXE
    - STONE_SHOVEL
    - STONE_SWORD
    - WOODEN_AXE
    - WOODEN_HOE
    - WOODEN_PICKAXE
    - WOODEN_SHOVEL
    - WOODEN_SWORD
    - LEATHER_BOOTS
    - LEATHER_CHESTPLATE
    - LEATHER_HELMET
    - LEATHER_HORSE_ARMOR
    - LEATHER_LEGGINGS
    - CHAINMAIL_BOOTS
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_HELMET
    - CHAINMAIL_LEGGINGS
    - TURTLE_HELMET
    - FLINT_AND_STEEL
    - SHEARS
    - FISHING_ROD