/*
 * Copyright 2020 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.professions.bukkit.database.jooq;


import com.rpkit.professions.bukkit.database.jooq.tables.RpkitCharacterProfession;
import com.rpkit.professions.bukkit.database.jooq.tables.RpkitCharacterProfessionChangeCooldown;
import com.rpkit.professions.bukkit.database.jooq.tables.RpkitProfessionHidden;
import com.rpkit.professions.bukkit.database.jooq.tables.records.RpkitCharacterProfessionChangeCooldownRecord;
import com.rpkit.professions.bukkit.database.jooq.tables.records.RpkitCharacterProfessionRecord;
import com.rpkit.professions.bukkit.database.jooq.tables.records.RpkitProfessionHiddenRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>rpkit_professions</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RpkitCharacterProfessionRecord> KEY_RPKIT_CHARACTER_PROFESSION_PRIMARY = UniqueKeys0.KEY_RPKIT_CHARACTER_PROFESSION_PRIMARY;
    public static final UniqueKey<RpkitCharacterProfessionRecord> KEY_RPKIT_CHARACTER_PROFESSION_RPKIT_CHARACTER_PROFESSION_CHARACTER_ID_UINDEX = UniqueKeys0.KEY_RPKIT_CHARACTER_PROFESSION_RPKIT_CHARACTER_PROFESSION_CHARACTER_ID_UINDEX;
    public static final UniqueKey<RpkitCharacterProfessionChangeCooldownRecord> KEY_RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN_PRIMARY = UniqueKeys0.KEY_RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN_PRIMARY;
    public static final UniqueKey<RpkitCharacterProfessionChangeCooldownRecord> KEY_RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN_RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN_CHARACTER_ID_UINDEX = UniqueKeys0.KEY_RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN_RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN_CHARACTER_ID_UINDEX;
    public static final UniqueKey<RpkitProfessionHiddenRecord> KEY_RPKIT_PROFESSION_HIDDEN_PRIMARY = UniqueKeys0.KEY_RPKIT_PROFESSION_HIDDEN_PRIMARY;
    public static final UniqueKey<RpkitProfessionHiddenRecord> KEY_RPKIT_PROFESSION_HIDDEN_RPKIT_PROFESSION_HIDDEN_CHARACTER_ID_UINDEX = UniqueKeys0.KEY_RPKIT_PROFESSION_HIDDEN_RPKIT_PROFESSION_HIDDEN_CHARACTER_ID_UINDEX;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<RpkitCharacterProfessionRecord> KEY_RPKIT_CHARACTER_PROFESSION_PRIMARY = Internal.createUniqueKey(RpkitCharacterProfession.RPKIT_CHARACTER_PROFESSION, "KEY_rpkit_character_profession_PRIMARY", new TableField[] { RpkitCharacterProfession.RPKIT_CHARACTER_PROFESSION.CHARACTER_ID }, true);
        public static final UniqueKey<RpkitCharacterProfessionRecord> KEY_RPKIT_CHARACTER_PROFESSION_RPKIT_CHARACTER_PROFESSION_CHARACTER_ID_UINDEX = Internal.createUniqueKey(RpkitCharacterProfession.RPKIT_CHARACTER_PROFESSION, "KEY_rpkit_character_profession_rpkit_character_profession_character_id_uindex", new TableField[] { RpkitCharacterProfession.RPKIT_CHARACTER_PROFESSION.CHARACTER_ID }, true);
        public static final UniqueKey<RpkitCharacterProfessionChangeCooldownRecord> KEY_RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN_PRIMARY = Internal.createUniqueKey(RpkitCharacterProfessionChangeCooldown.RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN, "KEY_rpkit_character_profession_change_cooldown_PRIMARY", new TableField[] { RpkitCharacterProfessionChangeCooldown.RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN.CHARACTER_ID }, true);
        public static final UniqueKey<RpkitCharacterProfessionChangeCooldownRecord> KEY_RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN_RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN_CHARACTER_ID_UINDEX = Internal.createUniqueKey(RpkitCharacterProfessionChangeCooldown.RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN, "KEY_rpkit_character_profession_change_cooldown_rpkit_character_profession_change_cooldown_character_id_uindex", new TableField[] { RpkitCharacterProfessionChangeCooldown.RPKIT_CHARACTER_PROFESSION_CHANGE_COOLDOWN.CHARACTER_ID }, true);
        public static final UniqueKey<RpkitProfessionHiddenRecord> KEY_RPKIT_PROFESSION_HIDDEN_PRIMARY = Internal.createUniqueKey(RpkitProfessionHidden.RPKIT_PROFESSION_HIDDEN, "KEY_rpkit_profession_hidden_PRIMARY", new TableField[] { RpkitProfessionHidden.RPKIT_PROFESSION_HIDDEN.CHARACTER_ID }, true);
        public static final UniqueKey<RpkitProfessionHiddenRecord> KEY_RPKIT_PROFESSION_HIDDEN_RPKIT_PROFESSION_HIDDEN_CHARACTER_ID_UINDEX = Internal.createUniqueKey(RpkitProfessionHidden.RPKIT_PROFESSION_HIDDEN, "KEY_rpkit_profession_hidden_rpkit_profession_hidden_character_id_uindex", new TableField[] { RpkitProfessionHidden.RPKIT_PROFESSION_HIDDEN.CHARACTER_ID }, true);
    }
}
