/*
 * This file is generated by jOOQ.
 */
package com.rpkit.statbuilds.bukkit.database.jooq.rpkit;


import com.rpkit.statbuilds.bukkit.database.jooq.rpkit.tables.RpkitCharacterStatPoints;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in rpkit
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>rpkit.rpkit_character_stat_points</code>.
     */
    public static final RpkitCharacterStatPoints RPKIT_CHARACTER_STAT_POINTS = RpkitCharacterStatPoints.RPKIT_CHARACTER_STAT_POINTS;
}
