wand-item:
  ==: org.bukkit.inventory.ItemStack
  v: 2586
  type: STICK
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '{"extra":[{"text":"Wand"}],"text":""}'
    lore:
      - '{"extra":[{"text":"Creates selections"}],"text":""}'
caching:
  rpkit_selection:
    minecraft_profile_id:
      enabled: true
      size: 20