/*
 * This file is generated by jOOQ.
 */
package com.rpkit.stores.bukkit.database.jooq.rpkit.tables.records;


import com.rpkit.stores.bukkit.database.jooq.rpkit.tables.RpkitTimedPurchase;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitTimedPurchaseRecord extends UpdatableRecordImpl<RpkitTimedPurchaseRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1923903388;

    /**
     * Setter for <code>rpkit.rpkit_timed_purchase.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rpkit.rpkit_timed_purchase.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rpkit.rpkit_timed_purchase.purchase_id</code>.
     */
    public void setPurchaseId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rpkit.rpkit_timed_purchase.purchase_id</code>.
     */
    public Integer getPurchaseId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RpkitTimedPurchase.RPKIT_TIMED_PURCHASE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RpkitTimedPurchase.RPKIT_TIMED_PURCHASE.PURCHASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPurchaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPurchaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitTimedPurchaseRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitTimedPurchaseRecord value2(Integer value) {
        setPurchaseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitTimedPurchaseRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RpkitTimedPurchaseRecord
     */
    public RpkitTimedPurchaseRecord() {
        super(RpkitTimedPurchase.RPKIT_TIMED_PURCHASE);
    }

    /**
     * Create a detached, initialised RpkitTimedPurchaseRecord
     */
    public RpkitTimedPurchaseRecord(Integer id, Integer purchaseId) {
        super(RpkitTimedPurchase.RPKIT_TIMED_PURCHASE);

        set(0, id);
        set(1, purchaseId);
    }
}
