/*
 * This file is generated by jOOQ.
 */
package com.rpkit.payments.bukkit.database.jooq;


import com.rpkit.payments.bukkit.database.jooq.tables.RpkitPaymentGroup;
import com.rpkit.payments.bukkit.database.jooq.tables.RpkitPaymentGroupInvite;
import com.rpkit.payments.bukkit.database.jooq.tables.RpkitPaymentGroupMember;
import com.rpkit.payments.bukkit.database.jooq.tables.RpkitPaymentGroupOwner;
import com.rpkit.payments.bukkit.database.jooq.tables.RpkitPaymentNotification;


/**
 * Convenience access to all tables in rpkit_payments.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>rpkit_payments.rpkit_payment_group</code>.
     */
    public static final RpkitPaymentGroup RPKIT_PAYMENT_GROUP = RpkitPaymentGroup.RPKIT_PAYMENT_GROUP;

    /**
     * The table <code>rpkit_payments.rpkit_payment_group_invite</code>.
     */
    public static final RpkitPaymentGroupInvite RPKIT_PAYMENT_GROUP_INVITE = RpkitPaymentGroupInvite.RPKIT_PAYMENT_GROUP_INVITE;

    /**
     * The table <code>rpkit_payments.rpkit_payment_group_member</code>.
     */
    public static final RpkitPaymentGroupMember RPKIT_PAYMENT_GROUP_MEMBER = RpkitPaymentGroupMember.RPKIT_PAYMENT_GROUP_MEMBER;

    /**
     * The table <code>rpkit_payments.rpkit_payment_group_owner</code>.
     */
    public static final RpkitPaymentGroupOwner RPKIT_PAYMENT_GROUP_OWNER = RpkitPaymentGroupOwner.RPKIT_PAYMENT_GROUP_OWNER;

    /**
     * The table <code>rpkit_payments.rpkit_payment_notification</code>.
     */
    public static final RpkitPaymentNotification RPKIT_PAYMENT_NOTIFICATION = RpkitPaymentNotification.RPKIT_PAYMENT_NOTIFICATION;
}
