/*
 * Copyright 2022 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.notifications.bukkit.database.jooq.tables.records;


import com.rpkit.notifications.bukkit.database.jooq.tables.RpkitNotification;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitNotificationRecord extends UpdatableRecordImpl<RpkitNotificationRecord> implements Record6<Integer, Integer, String, String, LocalDateTime, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rpkit_notifications.rpkit_notification.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rpkit_notifications.rpkit_notification.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>rpkit_notifications.rpkit_notification.recipient_id</code>.
     */
    public void setRecipientId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>rpkit_notifications.rpkit_notification.recipient_id</code>.
     */
    public Integer getRecipientId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rpkit_notifications.rpkit_notification.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rpkit_notifications.rpkit_notification.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rpkit_notifications.rpkit_notification.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rpkit_notifications.rpkit_notification.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rpkit_notifications.rpkit_notification.time</code>.
     */
    public void setTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>rpkit_notifications.rpkit_notification.time</code>.
     */
    public LocalDateTime getTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>rpkit_notifications.rpkit_notification.read</code>.
     */
    public void setRead(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>rpkit_notifications.rpkit_notification.read</code>.
     */
    public Boolean getRead() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, String, LocalDateTime, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, String, LocalDateTime, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RpkitNotification.RPKIT_NOTIFICATION.ID;
    }

    @Override
    public Field<Integer> field2() {
        return RpkitNotification.RPKIT_NOTIFICATION.RECIPIENT_ID;
    }

    @Override
    public Field<String> field3() {
        return RpkitNotification.RPKIT_NOTIFICATION.TITLE;
    }

    @Override
    public Field<String> field4() {
        return RpkitNotification.RPKIT_NOTIFICATION.CONTENT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return RpkitNotification.RPKIT_NOTIFICATION.TIME;
    }

    @Override
    public Field<Boolean> field6() {
        return RpkitNotification.RPKIT_NOTIFICATION.READ;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getRecipientId();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public String component4() {
        return getContent();
    }

    @Override
    public LocalDateTime component5() {
        return getTime();
    }

    @Override
    public Boolean component6() {
        return getRead();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getRecipientId();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public String value4() {
        return getContent();
    }

    @Override
    public LocalDateTime value5() {
        return getTime();
    }

    @Override
    public Boolean value6() {
        return getRead();
    }

    @Override
    public RpkitNotificationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RpkitNotificationRecord value2(Integer value) {
        setRecipientId(value);
        return this;
    }

    @Override
    public RpkitNotificationRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public RpkitNotificationRecord value4(String value) {
        setContent(value);
        return this;
    }

    @Override
    public RpkitNotificationRecord value5(LocalDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public RpkitNotificationRecord value6(Boolean value) {
        setRead(value);
        return this;
    }

    @Override
    public RpkitNotificationRecord values(Integer value1, Integer value2, String value3, String value4, LocalDateTime value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RpkitNotificationRecord
     */
    public RpkitNotificationRecord() {
        super(RpkitNotification.RPKIT_NOTIFICATION);
    }

    /**
     * Create a detached, initialised RpkitNotificationRecord
     */
    public RpkitNotificationRecord(Integer id, Integer recipientId, String title, String content, LocalDateTime time, Boolean read) {
        super(RpkitNotification.RPKIT_NOTIFICATION);

        setId(id);
        setRecipientId(recipientId);
        setTitle(title);
        setContent(content);
        setTime(time);
        setRead(read);
    }
}
