name: rpk-feature-flags-bukkit
author: alyphen
version: @version@
main: com.rpkit.featureflags.bukkit.RPKFeatureFlagsBukkit
depend:
- rpk-core-bukkit
- rpk-player-lib-bukkit
- rpk-feature-flag-lib-bukkit
api-version: '1.15'