name: rpk-stats-bukkit
author: alyphen
version: @version@
main: com.rpkit.stats.bukkit.RPKStatsBukkit
depend:
- rpk-core-bukkit
- rpk-player-lib-bukkit
- rpk-character-lib-bukkit
- rpk-stat-lib-bukkit
api-version: '1.16'
commands:
  stats:
    description: Shows your stats
    usage: /<command>
permissions:
  rpkit.stats.command.stats:
    description: Allows viewing stats
    default: true