/*
 * This file is generated by jOOQ.
 */
package com.rpkit.store.bukkit.database.jooq.tables;


import com.rpkit.store.bukkit.database.jooq.Keys;
import com.rpkit.store.bukkit.database.jooq.RpkitStores;
import com.rpkit.store.bukkit.database.jooq.tables.records.RpkitTimedPurchaseRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitTimedPurchase extends TableImpl<RpkitTimedPurchaseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rpkit_stores.rpkit_timed_purchase</code>
     */
    public static final RpkitTimedPurchase RPKIT_TIMED_PURCHASE = new RpkitTimedPurchase();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitTimedPurchaseRecord> getRecordType() {
        return RpkitTimedPurchaseRecord.class;
    }

    /**
     * The column <code>rpkit_stores.rpkit_timed_purchase.id</code>.
     */
    public final TableField<RpkitTimedPurchaseRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>rpkit_stores.rpkit_timed_purchase.purchase_id</code>.
     */
    public final TableField<RpkitTimedPurchaseRecord, Integer> PURCHASE_ID = createField(DSL.name("purchase_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private RpkitTimedPurchase(Name alias, Table<RpkitTimedPurchaseRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitTimedPurchase(Name alias, Table<RpkitTimedPurchaseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>rpkit_stores.rpkit_timed_purchase</code> table
     * reference
     */
    public RpkitTimedPurchase(String alias) {
        this(DSL.name(alias), RPKIT_TIMED_PURCHASE);
    }

    /**
     * Create an aliased <code>rpkit_stores.rpkit_timed_purchase</code> table
     * reference
     */
    public RpkitTimedPurchase(Name alias) {
        this(alias, RPKIT_TIMED_PURCHASE);
    }

    /**
     * Create a <code>rpkit_stores.rpkit_timed_purchase</code> table reference
     */
    public RpkitTimedPurchase() {
        this(DSL.name("rpkit_timed_purchase"), null);
    }

    public <O extends Record> RpkitTimedPurchase(Table<O> child, ForeignKey<O, RpkitTimedPurchaseRecord> key) {
        super(child, key, RPKIT_TIMED_PURCHASE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : RpkitStores.RPKIT_STORES;
    }

    @Override
    public Identity<RpkitTimedPurchaseRecord, Integer> getIdentity() {
        return (Identity<RpkitTimedPurchaseRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RpkitTimedPurchaseRecord> getPrimaryKey() {
        return Keys.KEY_RPKIT_TIMED_PURCHASE_PRIMARY;
    }

    @Override
    public RpkitTimedPurchase as(String alias) {
        return new RpkitTimedPurchase(DSL.name(alias), this);
    }

    @Override
    public RpkitTimedPurchase as(Name alias) {
        return new RpkitTimedPurchase(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitTimedPurchase rename(String name) {
        return new RpkitTimedPurchase(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitTimedPurchase rename(Name name) {
        return new RpkitTimedPurchase(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
