/*
 * Copyright 2021 Ren Binden
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.banks.bukkit.database.jooq;


import com.rpkit.banks.bukkit.database.jooq.tables.RpkitBank;
import com.rpkit.banks.bukkit.database.jooq.tables.records.RpkitBankRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>rpkit_banks</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RpkitBankRecord> KEY_RPKIT_BANK_PRIMARY = UniqueKeys0.KEY_RPKIT_BANK_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<RpkitBankRecord> KEY_RPKIT_BANK_PRIMARY = Internal.createUniqueKey(RpkitBank.RPKIT_BANK, "KEY_rpkit_bank_PRIMARY", new TableField[] { RpkitBank.RPKIT_BANK.CHARACTER_ID, RpkitBank.RPKIT_BANK.CURRENCY_NAME }, true);
    }
}
