/*
 * Copyright 2020 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.essentials.bukkit.database.jooq;


import com.rpkit.essentials.bukkit.database.jooq.tables.RpkitLogMessagesEnabled;
import com.rpkit.essentials.bukkit.database.jooq.tables.RpkitPreviousLocation;
import com.rpkit.essentials.bukkit.database.jooq.tables.RpkitTrackingDisabled;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitEssentials extends SchemaImpl {

    private static final long serialVersionUID = -2013915160;

    /**
     * The reference instance of <code>rpkit_essentials</code>
     */
    public static final RpkitEssentials RPKIT_ESSENTIALS = new RpkitEssentials();

    /**
     * The table <code>rpkit_essentials.rpkit_log_messages_enabled</code>.
     */
    public final RpkitLogMessagesEnabled RPKIT_LOG_MESSAGES_ENABLED = RpkitLogMessagesEnabled.RPKIT_LOG_MESSAGES_ENABLED;

    /**
     * The table <code>rpkit_essentials.rpkit_previous_location</code>.
     */
    public final RpkitPreviousLocation RPKIT_PREVIOUS_LOCATION = RpkitPreviousLocation.RPKIT_PREVIOUS_LOCATION;

    /**
     * The table <code>rpkit_essentials.rpkit_tracking_disabled</code>.
     */
    public final RpkitTrackingDisabled RPKIT_TRACKING_DISABLED = RpkitTrackingDisabled.RPKIT_TRACKING_DISABLED;

    /**
     * No further instances allowed
     */
    private RpkitEssentials() {
        super("rpkit_essentials", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            RpkitLogMessagesEnabled.RPKIT_LOG_MESSAGES_ENABLED,
            RpkitPreviousLocation.RPKIT_PREVIOUS_LOCATION,
            RpkitTrackingDisabled.RPKIT_TRACKING_DISABLED);
    }
}
