/*
 * This file is generated by jOOQ.
 */
package com.rpkit.stores.bukkit.database.jooq.rpkit.tables;


import com.rpkit.stores.bukkit.database.jooq.rpkit.Indexes;
import com.rpkit.stores.bukkit.database.jooq.rpkit.Keys;
import com.rpkit.stores.bukkit.database.jooq.rpkit.Rpkit;
import com.rpkit.stores.bukkit.database.jooq.rpkit.tables.records.RpkitConsumablePurchaseRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitConsumablePurchase extends TableImpl<RpkitConsumablePurchaseRecord> {

    private static final long serialVersionUID = 377523431;

    /**
     * The reference instance of <code>rpkit.rpkit_consumable_purchase</code>
     */
    public static final RpkitConsumablePurchase RPKIT_CONSUMABLE_PURCHASE = new RpkitConsumablePurchase();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitConsumablePurchaseRecord> getRecordType() {
        return RpkitConsumablePurchaseRecord.class;
    }

    /**
     * The column <code>rpkit.rpkit_consumable_purchase.id</code>.
     */
    public final TableField<RpkitConsumablePurchaseRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>rpkit.rpkit_consumable_purchase.purchase_id</code>.
     */
    public final TableField<RpkitConsumablePurchaseRecord, Integer> PURCHASE_ID = createField("purchase_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit.rpkit_consumable_purchase.remaining_uses</code>.
     */
    public final TableField<RpkitConsumablePurchaseRecord, Integer> REMAINING_USES = createField("remaining_uses", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>rpkit.rpkit_consumable_purchase</code> table reference
     */
    public RpkitConsumablePurchase() {
        this(DSL.name("rpkit_consumable_purchase"), null);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_consumable_purchase</code> table reference
     */
    public RpkitConsumablePurchase(String alias) {
        this(DSL.name(alias), RPKIT_CONSUMABLE_PURCHASE);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_consumable_purchase</code> table reference
     */
    public RpkitConsumablePurchase(Name alias) {
        this(alias, RPKIT_CONSUMABLE_PURCHASE);
    }

    private RpkitConsumablePurchase(Name alias, Table<RpkitConsumablePurchaseRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitConsumablePurchase(Name alias, Table<RpkitConsumablePurchaseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RpkitConsumablePurchase(Table<O> child, ForeignKey<O, RpkitConsumablePurchaseRecord> key) {
        super(child, key, RPKIT_CONSUMABLE_PURCHASE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Rpkit.RPKIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RPKIT_CONSUMABLE_PURCHASE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RpkitConsumablePurchaseRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RPKIT_CONSUMABLE_PURCHASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RpkitConsumablePurchaseRecord> getPrimaryKey() {
        return Keys.KEY_RPKIT_CONSUMABLE_PURCHASE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RpkitConsumablePurchaseRecord>> getKeys() {
        return Arrays.<UniqueKey<RpkitConsumablePurchaseRecord>>asList(Keys.KEY_RPKIT_CONSUMABLE_PURCHASE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitConsumablePurchase as(String alias) {
        return new RpkitConsumablePurchase(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitConsumablePurchase as(Name alias) {
        return new RpkitConsumablePurchase(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitConsumablePurchase rename(String name) {
        return new RpkitConsumablePurchase(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitConsumablePurchase rename(Name name) {
        return new RpkitConsumablePurchase(name, null);
    }
}
