/*
 * Copyright 2020 Ren Binden
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.economy.bukkit.database.jooq.tables.records;


import com.rpkit.economy.bukkit.database.jooq.tables.RpkitCurrency;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitCurrencyRecord extends UpdatableRecordImpl<RpkitCurrencyRecord> implements Record7<Integer, String, String, String, Double, Integer, String> {

    private static final long serialVersionUID = 1000193332;

    /**
     * Setter for <code>rpkit_economy.rpkit_currency.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rpkit_economy.rpkit_currency.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rpkit_economy.rpkit_currency.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rpkit_economy.rpkit_currency.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rpkit_economy.rpkit_currency.name_singular</code>.
     */
    public void setNameSingular(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rpkit_economy.rpkit_currency.name_singular</code>.
     */
    public String getNameSingular() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rpkit_economy.rpkit_currency.name_plural</code>.
     */
    public void setNamePlural(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rpkit_economy.rpkit_currency.name_plural</code>.
     */
    public String getNamePlural() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rpkit_economy.rpkit_currency.rate</code>.
     */
    public void setRate(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>rpkit_economy.rpkit_currency.rate</code>.
     */
    public Double getRate() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>rpkit_economy.rpkit_currency.default_amount</code>.
     */
    public void setDefaultAmount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>rpkit_economy.rpkit_currency.default_amount</code>.
     */
    public Integer getDefaultAmount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>rpkit_economy.rpkit_currency.material</code>.
     */
    public void setMaterial(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>rpkit_economy.rpkit_currency.material</code>.
     */
    public String getMaterial() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, Double, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, Double, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RpkitCurrency.RPKIT_CURRENCY.ID;
    }

    @Override
    public Field<String> field2() {
        return RpkitCurrency.RPKIT_CURRENCY.NAME;
    }

    @Override
    public Field<String> field3() {
        return RpkitCurrency.RPKIT_CURRENCY.NAME_SINGULAR;
    }

    @Override
    public Field<String> field4() {
        return RpkitCurrency.RPKIT_CURRENCY.NAME_PLURAL;
    }

    @Override
    public Field<Double> field5() {
        return RpkitCurrency.RPKIT_CURRENCY.RATE;
    }

    @Override
    public Field<Integer> field6() {
        return RpkitCurrency.RPKIT_CURRENCY.DEFAULT_AMOUNT;
    }

    @Override
    public Field<String> field7() {
        return RpkitCurrency.RPKIT_CURRENCY.MATERIAL;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getNameSingular();
    }

    @Override
    public String component4() {
        return getNamePlural();
    }

    @Override
    public Double component5() {
        return getRate();
    }

    @Override
    public Integer component6() {
        return getDefaultAmount();
    }

    @Override
    public String component7() {
        return getMaterial();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getNameSingular();
    }

    @Override
    public String value4() {
        return getNamePlural();
    }

    @Override
    public Double value5() {
        return getRate();
    }

    @Override
    public Integer value6() {
        return getDefaultAmount();
    }

    @Override
    public String value7() {
        return getMaterial();
    }

    @Override
    public RpkitCurrencyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RpkitCurrencyRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public RpkitCurrencyRecord value3(String value) {
        setNameSingular(value);
        return this;
    }

    @Override
    public RpkitCurrencyRecord value4(String value) {
        setNamePlural(value);
        return this;
    }

    @Override
    public RpkitCurrencyRecord value5(Double value) {
        setRate(value);
        return this;
    }

    @Override
    public RpkitCurrencyRecord value6(Integer value) {
        setDefaultAmount(value);
        return this;
    }

    @Override
    public RpkitCurrencyRecord value7(String value) {
        setMaterial(value);
        return this;
    }

    @Override
    public RpkitCurrencyRecord values(Integer value1, String value2, String value3, String value4, Double value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RpkitCurrencyRecord
     */
    public RpkitCurrencyRecord() {
        super(RpkitCurrency.RPKIT_CURRENCY);
    }

    /**
     * Create a detached, initialised RpkitCurrencyRecord
     */
    public RpkitCurrencyRecord(Integer id, String name, String nameSingular, String namePlural, Double rate, Integer defaultAmount, String material) {
        super(RpkitCurrency.RPKIT_CURRENCY);

        set(0, id);
        set(1, name);
        set(2, nameSingular);
        set(3, namePlural);
        set(4, rate);
        set(5, defaultAmount);
        set(6, material);
    }
}
