/*
 * This file is generated by jOOQ.
*/
package com.rpkit.payments.bukkit.database.jooq.rpkit.tables.records;


import com.rpkit.payments.bukkit.database.jooq.rpkit.tables.RpkitPaymentGroupOwner;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitPaymentGroupOwnerRecord extends UpdatableRecordImpl<RpkitPaymentGroupOwnerRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -286657085;

    /**
     * Setter for <code>rpkit.rpkit_payment_group_owner.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rpkit.rpkit_payment_group_owner.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rpkit.rpkit_payment_group_owner.payment_group_id</code>.
     */
    public void setPaymentGroupId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rpkit.rpkit_payment_group_owner.payment_group_id</code>.
     */
    public Integer getPaymentGroupId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rpkit.rpkit_payment_group_owner.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>rpkit.rpkit_payment_group_owner.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RpkitPaymentGroupOwner.RPKIT_PAYMENT_GROUP_OWNER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RpkitPaymentGroupOwner.RPKIT_PAYMENT_GROUP_OWNER.PAYMENT_GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RpkitPaymentGroupOwner.RPKIT_PAYMENT_GROUP_OWNER.CHARACTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPaymentGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitPaymentGroupOwnerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitPaymentGroupOwnerRecord value2(Integer value) {
        setPaymentGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitPaymentGroupOwnerRecord value3(Integer value) {
        setCharacterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitPaymentGroupOwnerRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RpkitPaymentGroupOwnerRecord
     */
    public RpkitPaymentGroupOwnerRecord() {
        super(RpkitPaymentGroupOwner.RPKIT_PAYMENT_GROUP_OWNER);
    }

    /**
     * Create a detached, initialised RpkitPaymentGroupOwnerRecord
     */
    public RpkitPaymentGroupOwnerRecord(Integer id, Integer paymentGroupId, Integer characterId) {
        super(RpkitPaymentGroupOwner.RPKIT_PAYMENT_GROUP_OWNER);

        set(0, id);
        set(1, paymentGroupId);
        set(2, characterId);
    }
}
