/*
 * Copyright 2021 Ren Binden
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.rpkit.characters.bukkit.database.jooq;


import com.rpkit.characters.bukkit.database.jooq.tables.RpkitCharacter;
import com.rpkit.characters.bukkit.database.jooq.tables.RpkitNewCharacterCooldown;
import com.rpkit.characters.bukkit.database.jooq.tables.records.RpkitCharacterRecord;
import com.rpkit.characters.bukkit.database.jooq.tables.records.RpkitNewCharacterCooldownRecord;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>rpkit_characters</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RpkitCharacterRecord, Integer> IDENTITY_RPKIT_CHARACTER = Identities0.IDENTITY_RPKIT_CHARACTER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RpkitCharacterRecord> KEY_RPKIT_CHARACTER_PRIMARY = UniqueKeys0.KEY_RPKIT_CHARACTER_PRIMARY;
    public static final UniqueKey<RpkitNewCharacterCooldownRecord> KEY_RPKIT_NEW_CHARACTER_COOLDOWN_PRIMARY = UniqueKeys0.KEY_RPKIT_NEW_CHARACTER_COOLDOWN_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<RpkitCharacterRecord, Integer> IDENTITY_RPKIT_CHARACTER = Internal.createIdentity(RpkitCharacter.RPKIT_CHARACTER, RpkitCharacter.RPKIT_CHARACTER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<RpkitCharacterRecord> KEY_RPKIT_CHARACTER_PRIMARY = Internal.createUniqueKey(RpkitCharacter.RPKIT_CHARACTER, "KEY_rpkit_character_PRIMARY", new TableField[] { RpkitCharacter.RPKIT_CHARACTER.ID }, true);
        public static final UniqueKey<RpkitNewCharacterCooldownRecord> KEY_RPKIT_NEW_CHARACTER_COOLDOWN_PRIMARY = Internal.createUniqueKey(RpkitNewCharacterCooldown.RPKIT_NEW_CHARACTER_COOLDOWN, "KEY_rpkit_new_character_cooldown_PRIMARY", new TableField[] { RpkitNewCharacterCooldown.RPKIT_NEW_CHARACTER_COOLDOWN.PROFILE_ID }, true);
    }
}
