/*
 * This file is generated by jOOQ.
 */
package com.rpkit.professions.bukkit.database.jooq.rpkit.tables;


import com.rpkit.professions.bukkit.database.jooq.rpkit.Indexes;
import com.rpkit.professions.bukkit.database.jooq.rpkit.Keys;
import com.rpkit.professions.bukkit.database.jooq.rpkit.Rpkit;
import com.rpkit.professions.bukkit.database.jooq.rpkit.tables.records.RpkitCharacterProfessionExperienceRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitCharacterProfessionExperience extends TableImpl<RpkitCharacterProfessionExperienceRecord> {

    private static final long serialVersionUID = -1082627147;

    /**
     * The reference instance of <code>rpkit.rpkit_character_profession_experience</code>
     */
    public static final RpkitCharacterProfessionExperience RPKIT_CHARACTER_PROFESSION_EXPERIENCE = new RpkitCharacterProfessionExperience();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitCharacterProfessionExperienceRecord> getRecordType() {
        return RpkitCharacterProfessionExperienceRecord.class;
    }

    /**
     * The column <code>rpkit.rpkit_character_profession_experience.id</code>.
     */
    public final TableField<RpkitCharacterProfessionExperienceRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>rpkit.rpkit_character_profession_experience.character_id</code>.
     */
    public final TableField<RpkitCharacterProfessionExperienceRecord, Integer> CHARACTER_ID = createField("character_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rpkit.rpkit_character_profession_experience.profession</code>.
     */
    public final TableField<RpkitCharacterProfessionExperienceRecord, String> PROFESSION = createField("profession", org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>rpkit.rpkit_character_profession_experience.experience</code>.
     */
    public final TableField<RpkitCharacterProfessionExperienceRecord, Integer> EXPERIENCE = createField("experience", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>rpkit.rpkit_character_profession_experience</code> table reference
     */
    public RpkitCharacterProfessionExperience() {
        this(DSL.name("rpkit_character_profession_experience"), null);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_character_profession_experience</code> table reference
     */
    public RpkitCharacterProfessionExperience(String alias) {
        this(DSL.name(alias), RPKIT_CHARACTER_PROFESSION_EXPERIENCE);
    }

    /**
     * Create an aliased <code>rpkit.rpkit_character_profession_experience</code> table reference
     */
    public RpkitCharacterProfessionExperience(Name alias) {
        this(alias, RPKIT_CHARACTER_PROFESSION_EXPERIENCE);
    }

    private RpkitCharacterProfessionExperience(Name alias, Table<RpkitCharacterProfessionExperienceRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitCharacterProfessionExperience(Name alias, Table<RpkitCharacterProfessionExperienceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RpkitCharacterProfessionExperience(Table<O> child, ForeignKey<O, RpkitCharacterProfessionExperienceRecord> key) {
        super(child, key, RPKIT_CHARACTER_PROFESSION_EXPERIENCE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Rpkit.RPKIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RPKIT_CHARACTER_PROFESSION_EXPERIENCE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RpkitCharacterProfessionExperienceRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RPKIT_CHARACTER_PROFESSION_EXPERIENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RpkitCharacterProfessionExperienceRecord> getPrimaryKey() {
        return Keys.KEY_RPKIT_CHARACTER_PROFESSION_EXPERIENCE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RpkitCharacterProfessionExperienceRecord>> getKeys() {
        return Arrays.<UniqueKey<RpkitCharacterProfessionExperienceRecord>>asList(Keys.KEY_RPKIT_CHARACTER_PROFESSION_EXPERIENCE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitCharacterProfessionExperience as(String alias) {
        return new RpkitCharacterProfessionExperience(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RpkitCharacterProfessionExperience as(Name alias) {
        return new RpkitCharacterProfessionExperience(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitCharacterProfessionExperience rename(String name) {
        return new RpkitCharacterProfessionExperience(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitCharacterProfessionExperience rename(Name name) {
        return new RpkitCharacterProfessionExperience(name, null);
    }
}
